[[window]]
name = "dotfilesxc"
path = "~/Downloads/dotfilesxc"

[[window]]
name = "playbook"
path = "~/moxconf/development/linux-void"
startup_script = "source .venv/bin/activate"

[[window]]
name = "videos"
path = "~/Downloads/screenshot/videos"
startup_script = "yazi"

[[window]]
name = "notes"
path = "~/Dropbox/neorg"

[[window]]
name = "vimrc"
path = "~/moxconf/development/dotfiles"
# startup_script = "vpack"

[[window]]
name = "Downloads"
path = "~/Downloads"
# startup_script = "sleep 2 && tmux split-window -h -R 50 && yazi "
startup_script = "yazi"

[[window]]
name = ".config"
path = "~/.config"

[[window]]
name = "Lazy"
path = "~/.local/share/nvim/lazy"
startup_script = "ll"

[[window]]
name = "Vim-pack"
path = "~/.local/share/nvim/site/pack/core/opt"
startup_script = "ll"

# +------------------------------------------------------------------------------+
# | DOTFILES                                                                     |
# +------------------------------------------------------------------------------+

[[session]]
name = "Dotfiles"
path = "~/moxconf/development/dotfiles"
startup_command = "v"
windows = ["dotfilesxc", "notes", ".config", "Lazy", "Vim-pack"]

# +------------------------------------------------------------------------------+
# | ANSIBLE PLAYBOOK                                                             |
# +------------------------------------------------------------------------------+

[[session]]
name = "Linuxvoid"
path = "~/moxconf/development/linux-void"
startup_command = "source .venv/bin/activate"
windows = ["playbook"]

# +------------------------------------------------------------------------------+
# | IMAGE & VIDEO                                                                |
# +------------------------------------------------------------------------------+

[[session]]
name = "Image&Video"
path = "~/Downloads/screenshot"
startup_command = "yazi"
windows = ["videos", "Downloads"]

# +------------------------------------------------------------------------------+
# | PROJECT                                                                      |
# +------------------------------------------------------------------------------+

[[session]]
name = "Typescript"
path = "~/moxconf/development/project/typescript"
disable_startup_command = true

[[session]]
name = "Rust"
path = "~/moxconf/development/project/rust"
disable_startup_command = true

[[session]]
name = "Golang"
path = "~/moxconf/development/project/golang"
disable_startup_command = true

[[session]]
name = "Python"
path = "~/moxconf/development/project/python"
disable_startup_command = true

[[session]]
name = "Bot"
path = "~/moxconf/development/project/misc"
startup_command = ""

[[session]]
name = "Nvimplugin"
path = "~/.local/src/nvim_plugins"
startup_command = ""
