# vim:fileencoding=utf-8:foldmethod=marker

# Taken from: https://github.com/yazi-rs/flavors?tab=readme-ov-file

# : Manager {{{

[manager]
cwd = { fg = "#3f3f3f" }

hovered = { bg = "#202623" }
preview_hovered = { fg = "#78b0a8", bg = "#1e2323" }

find_keyword = { fg = "#313b35", bg = "#e69875", italic = true }
find_position = { fg = "#d6a56f", bg = "reset", italic = true }

marker_copied = { fg = "#dbbc7f", bg = "#dbbc7f" }
marker_cut = { fg = "#e67e80", bg = "#e67e80" }
marker_selected = { fg = "#fe8019", bg = "#fe8019" }

count_cut = { fg = "#d6a56f", bg = "#232828" }
count_copied = { fg = "#e67e80", bg = "#232828" }
count_selected = { fg = "#fe8019", bg = "#232828" }

tab_active = { fg = "#709671", bg = "#3e533f" }
tab_inactive = { fg = "#3c4444", bg = "#232828" }
tab_width = 1

border_symbol = "│"
border_style = { fg = "#262b2b" }

# : }}}

[mode]
normal_main = { fg = "#323a3a", bg = "#7da77e", bold = true }
normal_alt = { fg = "#7da77e", bg = "#323a3a" }

select_main = { fg = "#ffffff", bg = "#223249", bold = true }
select_alt = { fg = "#223249", bg = "#ffffff" }

unset_main = { fg = "#ffffff", bg = "#d3869b", bold = true }
unset_alt = { fg = "#d3869b", bg = "#ffffff" }


# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#313b35", bg = "#313b35" }

progress_label = { fg = "#d6a56f", bold = true }
progress_normal = { fg = "#d6a56f", bg = "#313b35" }
progress_error = { fg = "#181b1b", bg = "#e67e80" }

perm_type = { fg = "#8caaee" }
perm_read = { fg = "#e5c890" }
perm_write = { fg = "#e78284" }
perm_exec = { fg = "#a6d189" }
perm_sep = { fg = "#838ba7" }

# : }}}


# : Input {{{

[input]
border = { fg = "#7a8478" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border = { fg = "#7a8478" }
active = { fg = "#7da77e" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#7a8478" }
title = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#1f2323" }
cand = { fg = "#78b0a8" }
rest = { fg = "#e69875" }
desc = { fg = "#dbbc7f" }
separator = "  "
separator_style = { fg = "#c3c082" }

# : }}}


# : Help {{{

[help]
on = { fg = "#e69875" }
run = { fg = "#dbbc7f" }
desc = { fg = "#7a8478" }
hovered = { bg = "#202623", bold = true }
footer = { fg = "#7a8478", bg = "#1e2323" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Media
  { mime = "image/*", fg = "#c76f82" },
  { mime = "{audio,video}/*", fg = "#dbbc7f" },

  # Archives
  { mime = "application/{,g}zip", fg = "#e67e80" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e67e80" },

  # Fallback
  { name = "*", fg = "#cccccc" },
  { name = "*/", fg = "#a7c080" },
]

# : }}}
