#!/bin/bash

clear

# shellcheck disable=SC1090,SC1091
. "$(dirname "$0")"/.nnn-plugin-helper

if ! type fzf >/dev/null 2>&1; then
	printf "fzf missing"
	read -r _
	exit 1
fi

if not_in_tmux; then
	select="$(echo -e 'Grep string in file\nSearch name of file' | fzf)"
else
	select="$(echo -e 'Grep string in file\nSearch name of file' | fzf-tmux -xC -w '60%' -h '50%')"
fi

if [[ "$select" == "Grep string in file" ]]; then
	res="$(
		RG_PREFIX="rg --column --line-number --no-heading --hidden --follow --color=always \
              --smart-case "
		FZF_DEFAULT_COMMAND="$RG_PREFIX ''" \
			fzf-tmux --bind "change:reload:$RG_PREFIX {q} || true" \
			--ansi --layout=reverse -xC -w '80%' -h '80%' --header "$select" |
			cut -d':' -f1
	)"
elif [[ "$select" == "Search name of file" ]]; then
	res="$(
		RG_PREFIX="fd --color=never --type f --hidden --follow --exclude .git "
		FZF_DEFAULT_COMMAND="$RG_PREFIX ''" \
			fzf-tmux --bind "change:reload:$RG_PREFIX {q} || true" \
			--ansi --layout=reverse -xC -w '80%' -h '80%' --header "$select" |
			cut -d':' -f1
	)"
fi

[ -n "$res" ] && nnn "$res"
