[languages]
rust = ["rustfmt"]
go = ["gofmt"]
sh = ["shfmt"]
bash = ["shfmt"]
kotlin = ["ktlin"]
json = ["prettier"]
typescript = ["prettier --parser typescript"]
javascript = ["prettier --parser babel"]
ts = ["prettier --parser typescript"]
js = ["prettier --parser babel"]
lua = ["stylua -s -"]
# python = ["black --fast -"]
python = ["ruff"]
