# Taken from: https://github.com/yazi-rs/flavors?tab=readme-ov-file

# : Manager {{{

[manager]
cwd = { fg = "#6b645f" }

# Hovered
hovered = { bg = "#3f362e" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#1b1b1b", bg = "#3ddbd9", italic = true }
find_position = { fg = "#fe8019", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#e49b5d", bg = "#e49b5d" }
marker_copied = { fg = "#b380b0", bg = "#b380b0" }
marker_cut = { fg = "#bd8183", bg = "#bd8183" }

count_selected = { fg = "#e49b5d", bg = "#423224" }
count_copied = { fg = "#b380b0", bg = "#423224" }
count_cut = { fg = "#bd8183", bg = "#423224" }

# Tab
tab_active = { fg = "#cd8b53", bg = "#724d2e" }
tab_inactive = { fg = "#775538", bg = "#423224" }

# Border
border_symbol = "│"
border_style = { fg = "#1c1c1c" }

# Highlighting
# syntect_theme = "~/.config/yazi/Gruvbox-Dark.tmTheme"

# : }}}

[mode]
normal_main = { fg = "#8a613e", bg = "#3f3023", bold = true }
normal_alt = { fg = "#8a613e", bg = "#423224" }

select_main = { fg = "#ffffff", bg = "#2a2a2a", bold = true }
select_alt = { fg = "#223249", bg = "#ffffff" }

unset_main = { fg = "#ffffff", bg = "#d3869b", bold = true }
unset_alt = { fg = "#d3869b", bg = "#ffffff" }

# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#6b6461", bg = "#181818" }

# Progress
progress_label = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#504945", bg = "#3c3836" }
progress_error = { fg = "#fb4934", bg = "#3c3836" }

# Permissions
perm_type = { fg = "#8caaee" }
perm_read = { fg = "#e5c890" }
perm_write = { fg = "#e78284" }
perm_exec = { fg = "#a6d189" }
perm_sep = { fg = "#838ba7" }

# : }}}


# : Input {{{

[input]
border = { fg = "#bdae93" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border = { fg = "#504945" }
active = { fg = "#fe8019" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#504945" }
title = {}
hovered = { underline = true }

# : }}}


# :  {{{

[which]
mask = { bg = "#3a332c" }
cand = { fg = "#83a598" }
rest = { fg = "#928374" }
desc = { fg = "#fe8019" }
separator = "  "
separator_style = { fg = "#504945" }

# : }}}


# : Help {{{

[help]
on = { fg = "#fe8019" }
exec = { fg = "#83a598" }
desc = { fg = "#928374" }
hovered = { bg = "#6b645f", bold = true }
footer = { fg = "#3c3836", bg = "#a89984" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#83a598" },

  # Videos
  { mime = "video/*", fg = "#b8bb26" },
  { mime = "audio/*", fg = "#b8bb26" },

  # Archives
  { mime = "application/zip", fg = "#fe8019" },
  { mime = "application/gzip", fg = "#fe8019" },
  { mime = "application/x-tar", fg = "#fe8019" },
  { mime = "application/x-bzip", fg = "#fe8019" },
  { mime = "application/x-bzip2", fg = "#fe8019" },
  { mime = "application/x-7z-compressed", fg = "#fe8019" },
  { mime = "application/x-rar", fg = "#fe8019" },

  # Fallback
  { name = "*", fg = "#ffe894" },
  { name = "*/", fg = "#ebc06d" },
]

# : }}}
