# Taken from: https://github.com/yazi-rs/flavors?tab=readme-ov-file

# : Manager {{{

[mgr]
cwd = { fg = "#4b4b4b" }

# Hovered
hovered = { bg = "#2f2f2f" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#1b1b1b", bg = "#3ddbd9", italic = true }
find_position = { fg = "#fe8019", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#ffba7b", bg = "#ffba7b" }
marker_copied = { fg = "#e1c0fa", bg = "#e1c0fa" }
marker_cut = { fg = "#e27373", bg = "#e27373" }

count_selected = { fg = "#ffba7b", bg = "#2f2f2f" }
count_copied = { fg = "#e1c0fa", bg = "#2f2f2f" }
count_cut = { fg = "#e27373", bg = "#2f2f2f" }

# Tab
tab_active = { fg = "#e18be1", bg = "#704570" }
tab_inactive = { fg = "#5e5e5e", bg = "#2f2f2f" }

# Border
border_symbol = "│"
border_style = { fg = "#1c1c1c" }

# Highlighting
# syntect_theme = "~/.config/yazi/Gruvbox-Dark.tmTheme"

# : }}}

[mode]
normal_main = { fg = "#4d4d4d", bg = "#232323", bold = true }
normal_alt = { fg = "#4d4d4d", bg = "#2f2f2f" }

select_main = { fg = "#ffffff", bg = "#2a2a2a", bold = true }
select_alt = { fg = "#223249", bg = "#ffffff" }

unset_main = { fg = "#ffffff", bg = "#d3869b", bold = true }
unset_alt = { fg = "#d3869b", bg = "#ffffff" }

# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#6b6461", bg = "#181818" }

# Progress
progress_label = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#504945", bg = "#3c3836" }
progress_error = { fg = "#fb4934", bg = "#3c3836" }

# Permissions
perm_type = { fg = "#8caaee" }
perm_read = { fg = "#e5c890" }
perm_write = { fg = "#e78284" }
perm_exec = { fg = "#a6d189" }
perm_sep = { fg = "#838ba7" }

# : }}}


# : Input {{{

[input]
border = { fg = "#bdae93" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border = { fg = "#504945" }
active = { fg = "#fe8019" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#504945" }
title = {}
hovered = { underline = true }

# : }}}


# :  {{{

[which]
mask = { bg = "#151515" }
cand = { fg = "#83a598" }
rest = { fg = "#928374" }
desc = { fg = "#fe8019" }
separator = "  "
separator_style = { fg = "#504945" }

# : }}}


# : Help {{{

[help]
on = { fg = "#fe8019" }
exec = { fg = "#83a598" }
desc = { fg = "#928374" }
hovered = { bg = "#4b4b4b", bold = true }
footer = { fg = "#3c3836", bg = "#a89984" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#83a598" },

  # Videos
  { mime = "video/*", fg = "#b8bb26" },
  { mime = "audio/*", fg = "#b8bb26" },

  # Archives
  { mime = "application/zip", fg = "#fe8019" },
  { mime = "application/gzip", fg = "#fe8019" },
  { mime = "application/x-tar", fg = "#fe8019" },
  { mime = "application/x-bzip", fg = "#fe8019" },
  { mime = "application/x-bzip2", fg = "#fe8019" },
  { mime = "application/x-7z-compressed", fg = "#fe8019" },
  { mime = "application/x-rar", fg = "#fe8019" },

  # Fallback
  { name = "*", fg = "#b8b8b8" },
  { name = "*/", fg = "#8fa5cd" },
]

# : }}}
