# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#48486e" }

# Hovered
hovered = { bg = "#2c293e" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#2c293e", bg = "#7ec9d8", bold = true, italic = true, underline = true }
find_position = { fg = "#f5c2e7", bg = "reset", bold = true, italic = true }

# Marker
marker_selected = { fg = "#fe8019", bg = "#fe8019" }
marker_copied = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut = { fg = "#f38ba8", bg = "#f38ba8" }

# Count
count_copied = { bg = "#2b2b42", fg = "#a6e3a1" }
count_cut = { bg = "#2b2b42", fg = "#f38ba8" }
count_selected = { bg = "#2b2b42", fg = "#f9e2af" }

# Tab
tab_active = { fg = "#b695de", bg = "#65537b" }
tab_inactive = { fg = "#48486d", bg = "#2b2b42" }
tab_width = 1

# Border
border_symbol = "│"
border_style = { fg = "#303049" }

# : }}}

[mode]
normal_main = { fg = "#212133", bg = "#cba6f7", bold = true }
normal_alt = { fg = "#cba6f7", bg = "#212133" }

select_main = { fg = "#ffffff", bg = "#45475a", bold = true }
select_alt = { fg = "#223249", bg = "#ffffff" }

unset_main = { fg = "#ffffff", bg = "#d3869b", bold = true }
unset_alt = { fg = "#d3869b", bg = "#ffffff" }

# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#45475a", bg = "#45475a" }

# Progress
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#89b4fa", bg = "#45475a" }
progress_error = { fg = "#f38ba8", bg = "#45475a" }

# Permissions
perm_type = { fg = "#8caaee" }
perm_read = { fg = "#e5c890" }
perm_write = { fg = "#e78284" }
perm_exec = { fg = "#a6d189" }
perm_sep = { fg = "#838ba7" }

# : }}}


# : Select {{{

[select]
border = { fg = "#89b4fa" }
active = { fg = "#f5c2e7", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "#89b4fa" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border = { fg = "#89b4fa" }

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#89b4fa" }
title = {}
hovered = { fg = "#f5c2e7", underline = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#27273b" }
cand = { fg = "#94e2d5" }
rest = { fg = "#9399b2" }
desc = { fg = "#f5c2e7" }
separator = "  "
separator_style = { fg = "#585b70" }

# : }}}


# : Help {{{

[help]
on = { fg = "#94e2d5" }
run = { fg = "#f5c2e7" }
hovered = { bg = "#2c293e", bold = true }
footer = { fg = "#45475a", bg = "#cdd6f4" }

# : }}}


# : Notify {{{

[notify]
title_info = { fg = "#a6e3a1" }
title_warn = { fg = "#f9e2af" }
title_error = { fg = "#f38ba8" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#94e2d5" },

  # Media
  { mime = "{audio,video}/*", fg = "#f9e2af" },

  # Archives
  { mime = "application/*zip", fg = "#f5c2e7" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f5c2e7" },

  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#a6e3a1" },

  # Fallback
  { name = "*", fg = "#cdd6f4" },
  { name = "*/", fg = "#89b4fa" },
]

# : }}}
