# vim:fileencoding=utf-8:foldmethod=marker

# Taken from: https://github.com/yazi-rs/flavors?tab=readme-ov-file

# : Manager {{{

[manager]
cwd = { fg = "#545356" }

hovered = { bg = "#1d1d23" }
preview_hovered = { fg = "#559ba3", bg = "#1d1d22" }

find_keyword = { fg = "#1d1d23", bg = "#e3a462", italic = true }
find_position = { fg = "#abbceb", bg = "reset", italic = true }

marker_selected = { fg = "#fe8019", bg = "#fe8019" }
marker_copied = { fg = "#b8bb26", bg = "#b8bb26" }
marker_cut = { fg = "#f38ba8", bg = "#f38ba8" }

count_cut = { fg = "#f38ba8", bg = "#202027" }
count_copied = { fg = "#b8bb26", bg = "#202027" }
count_selected = { fg = "#fe8019", bg = "#202027" }

tab_active = { fg = "#7c7ac5", bg = "#45446d" }
tab_inactive = { fg = "#39393e", bg = "#202027" }
tab_width = 1

border_symbol = "│"
border_style = { fg = "#555568" }

# : }}}

[mode]
normal_main = { fg = "#2f2f38", bg = "#8a88db", bold = true }
normal_alt = { fg = "#8a88db", bg = "#2f2f38" }

select_main = { fg = "#ffffff", bg = "#223249", bold = true }
select_alt = { fg = "#223249", bg = "#ffffff" }

unset_main = { fg = "#ffffff", bg = "#d3869b", bold = true }
unset_alt = { fg = "#d3869b", bg = "#ffffff" }

# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "#2a2a31", bg = "#25252c" }

progress_label = { fg = "#abbceb", bold = true }
progress_normal = { fg = "#abbceb", bg = "#2a2a31" }
progress_error = { fg = "#171719", bg = "#e67e80" }

perm_type = { fg = "#8caaee" }
perm_read = { fg = "#e5c890" }
perm_write = { fg = "#e78284" }
perm_exec = { fg = "#a6d189" }
perm_sep = { fg = "#838ba7" }

# : }}}


# : Input {{{

[input]
border = { fg = "#555568" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border = { fg = "#555568" }
active = { fg = "#8a88db" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "#555568" }
title = {}
hovered = { underline = true }

# : }}}


# :  {{{

[which]
mask = { bg = "#1d1d20" }
cand = { fg = "#559ba3" }
rest = { fg = "#e3a462" }
desc = { fg = "#7da77e" }
separator = "  "
separator_style = { fg = "#9b99a3" }

# : }}}


# : Help {{{

[help]
on = { fg = "#e3a462" }
run = { fg = "#7da77e" }
desc = { fg = "#555568" }
hovered = { bg = "#1d1d23", bold = true }
footer = { fg = "#555568", bg = "#1d1d22" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Media
  { mime = "image/*", fg = "#e89bce" },
  { mime = "{audio,video}/*", fg = "#7da77e" },

  # Archives
  { mime = "application/{,g}zip", fg = "#e67e80" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e67e80" },

  # Fallback
  { name = "*", fg = "#bbbac1" },
  { name = "*/", fg = "#8a88db" },
]

# : }}}
