local add_on_event = require("vim-pack").add_on_event

local ConfigPath = require("config").path

add_on_event("UIEnter", {
  {
    src = "xheisenbugx/org.nvim",

    -- setup = false,
    -- dependencies = {
    --   {
    --     "lukas-reineke/headlines.nvim",
    --     ft = { "org" },
    --     opts = {
    --       markdown = {
    --         headline_highlights = false,
    --         codeblock_highlight = false,
    --         quote_highlight = false,
    --         bullet_highlights = false,
    --       },
    --       org = {
    --         headline_highlights = { "Headline1", "Headline2", "Headline3", "Headline4", "Headline5", "Headline6" },
    --         codeblock_highlight = "CodeBlock",
    --         dash_highlight = "Dash",
    --         dash_string = "-",
    --         doubledash_highlight = "DoubleDash",
    --         doubledash_string = "=",
    --         quote_highlight = "@markup.quote.markdown",
    --         quote_string = "┃",
    --         fat_headlines = false,
    --         fat_headline_upper_string = "▃",
    --         fat_headline_lower_string = "🬂",
    --       },
    --     },
    --   },
    -- },
    -- lazy = false,
    opts = function()
      local H = require "utils.highlights"
      local codeblock_bg = H.get("CodeBlock", "bg")
      local codeblocktext_bg = H.get("CodeBlockFiletypeText", "bg")
      local codeblockjson_bg = H.get("CodeBlockFiletypeJson", "bg")
      local codeblockDb_bg = H.get("CodeBlockFiletypeDb", "bg")

      return {
        picker = "snacks",

        picker_opts = {
          winopts = {},
        },
        picker_keys = { split = "<C-s>", vsplit = "<C-v>", tab = "<C-t>", qflist = "<c-q>" },

        org_directory = { ConfigPath.wiki_path },
        -- agenda_files = { string.format("%s/**/*", ConfigPath.wiki_path) },
        agenda_files = { string.format("%s/orgmode/**/*", ConfigPath.wiki_path) },
        default_notes_file = string.format("%s/orgmode/gtd/refile.org", ConfigPath.wiki_path),

        -- src_preserve_indentation = true,
        -- adapt_indentation = true,

        -- indent_mode = false,
        -- default_notes_file = "~/org/refile.org",
        ui = {
          hide_emphasis_markers = true,
          src_block_faces = {
            python = { bg = codeblock_bg },
            bash = { bg = codeblock_bg },
            rust = { bg = codeblock_bg },
            sql = { bg = codeblockDb_bg },
            java = { bg = codeblock_bg },
            text = { bg = codeblocktext_bg },
            css = { bg = codeblock_bg },
            html = { bg = codeblock_bg },
            json = { bg = codeblockjson_bg },
            http = { bg = codeblock_bg },
            cfg = { bg = codeblock_bg },
            lua = { bg = codeblock_bg },
            php = { bg = codeblock_bg },
            go = { bg = codeblock_bg },
            typescript = { bg = codeblock_bg },
            javascript = { bg = codeblock_bg },
            tsx = { bg = codeblock_bg },
          },
          --   indent_mode = true,
          --   indent_indentation_per_level = 2,
          --   hide_leading_stars = true,
          --   --   -- hide_emphasis_markers = true,
          --   --
          --   --   -- imenu_depth = 5,
          --   --
          --   --   -- indent_mode = false,
          --   --   -- indent_mode = true,
        },
        --
        mappings = {
          disable_all = false,
          prefix = "<LocalLeader>a",
          global = {
            agenda = "<prefix>a",
            capture = "<prefix>c",
            store_link = "<prefix>ls",
            goto_heading = "<prefix>g",
            clock_goto = "<prefix>xj",
            clock_out = "<prefix>xo",
            clock_cancel = "<prefix>xq",
          },
          org = {
            help = "g?",
            -- visibility
            cycle = "<Tab>",
            global_cycle = "<S-Tab>",
            -- context / links
            context_action = { "<C-c><C-c>", "<prefix><CR>" },
            open_at_point = { "<CR>", "gx", "<prefix>o" },
            -- structure
            meta_return = "<M-CR>",
            meta_shift_return = "<M-S-CR>",
            insert_heading = "<prefix>ih",
            insert_todo_heading = "<prefix>it",
            insert_subheading = "<prefix>is",
            insert_drawer = "<prefix>id",
            insert_structure_template = "<prefix>ib",
            insert_footnote = "<prefix>if",
            promote_heading = "<<",
            demote_heading = ">>",
            promote_subtree = "<s",
            demote_subtree = ">s",
            meta_left = "<M-Left>",
            meta_right = "<M-Right>",
            meta_up = "<M-Up>",
            meta_down = "<M-Down>",
            shift_meta_left = "<C-c><M-H>",
            shift_meta_right = "<C-c><M-L>",
            shift_meta_up = "<C-c><M-K>",
            shift_meta_down = "<C-c><M-J>",
            move_subtree_up = "<prefix>K",
            move_subtree_down = "<prefix>J",
            copy_subtree = "<prefix>hy",
            cut_subtree = "<prefix>hd",
            paste_subtree = "<prefix>hp",
            clone_subtree = "<prefix>hc",
            sort = "<prefix>hs",
            narrow_subtree = "<prefix>hn",
            toggle_comment = "<prefix>hC",
            toggle_archive_tag = "<prefix>hA",
            toggle_heading = "<prefix>*",
            toggle_item = "<prefix>-",
            emphasize = "<prefix>E",
            mark_element = "<prefix>v",
            narrow_block = "<prefix>nb",
            narrow_element = "<prefix>ne",
            goto_parent = "g{",
            next_heading = "<M-n>",
            prev_heading = "<M-p>",
            next_sibling = "][",
            prev_sibling = "[]",
            buffer_goto = "<prefix>.",
            -- todo / priority / tags / properties
            todo_next = "cit",
            todo_prev = "ciT",
            shift_right = "<S-Right>",
            shift_left = "<S-Left>",
            todo_select = "<prefix>T",
            shift_up = "<S-Up>",
            shift_down = "<S-Down>",
            increment = "<C-a>",
            decrement = "<C-x>",
            priority = "<prefix>,",
            set_tags = "<prefix>t",
            set_property = "<prefix>p",
            delete_property = "<prefix>P",
            id_get_create = "<prefix>lI",
            -- dates
            schedule = "<prefix>s",
            deadline = "<prefix>d",
            timestamp = "<prefix>i.",
            timestamp_inactive = "<prefix>i!",
            -- lists
            toggle_checkbox = "<C-Space>",
            update_statistics = "<prefix>#",
            cycle_bullet = "<prefix>hb",
            -- clock
            clock_in = "<prefix>xi",
            clock_out = "<prefix>xo",
            clock_cancel = "<prefix>xq",
            clock_goto = "<prefix>xj",
            set_effort = "<prefix>xe",
            inc_effort = "<prefix>xE",
            clock_modify_effort = "<prefix>xm",
            clock_resolve = "<prefix>xz",
            clock_report = "<prefix>xr",
            clock_display = "<prefix>xd",
            link_preview = "<prefix>xv",
            link_preview_refresh = "<prefix>xV",
            latex_preview = "<prefix>xl",
            dblock_update = "<prefix>xu",
            dblock_update_all = "<prefix>xU",
            column_view = "<prefix>C",
            -- links
            insert_link = "<prefix>li",
            store_link = "<prefix>ls",
            toggle_link_display = "<prefix>lt",
            next_link = "<prefix>ln",
            prev_link = "<prefix>lp",
            insert_last_stored_link = "<prefix>lL",
            insert_all_links = "<prefix>lA",
            id_goto = "<prefix>lg",
            id_copy = "<prefix>ly",
            -- refile / archive / attach
            refile = "<prefix>r",
            refile_copy = "<prefix>R",
            archive_subtree = "<prefix>$",
            attach = "<prefix>A",
            -- search / export
            sparse_tree = "<prefix>/",
            export = "<prefix>e",
            -- tables
            table_create = "<prefix>Tc",
            table_insert_hline = "<prefix>T-",
            table_recalc = "<prefix>Tf",
            table_sort = "<prefix>Ts",
            table_insert_row = "<prefix>Tr",
            table_delete_row = "<prefix>TR",
            table_insert_column = "<prefix>Ti",
            table_delete_column = "<prefix>TI",
            table_copy_down = "<S-CR>",
            table_transpose = "<prefix>Tt",
            table_rotate_marks = "<prefix>T#",
            -- babel
            edit_special = "<prefix>`",
            babel_execute = "<prefix>be",
            babel_execute_buffer = "<prefix>bb",
            babel_execute_subtree = "<prefix>bs",
            babel_tangle = "<prefix>bt",
            babel_remove_result = "<prefix>bk",
            babel_next_block = "<prefix>bn",
            babel_prev_block = "<prefix>bp",
            babel_tangle_file = "<prefix>bf",
            babel_expand = "<prefix>bv",
            babel_view_info = "<prefix>bI",
            babel_check = "<prefix>bc",
            babel_insert_header_arg = "<prefix>bj",
            babel_goto_named = "<prefix>bg",
            babel_goto_named_result = "<prefix>br",
            babel_goto_head = "<prefix>bu",
            babel_open_result = "<prefix>bo",
            babel_demarcate = "<prefix>bd",
            babel_lob_ingest = "<prefix>bi",
            babel_load_in_session = "<prefix>bl",
            babel_switch_to_session = "<prefix>bz",
            babel_switch_to_session_with_code = "<prefix>bZ",
            babel_kill_session = "<prefix>bK",
            babel_sha1_hash = "<prefix>ba",
            babel_describe_bindings = "<prefix>bh",
            babel_mark_block = "<prefix>bm",
            babel_do_key_sequence = "<prefix>bx",
          },
          --- Insert-mode mappings inside org buffers.
          org_insert = {
            meta_return = "<M-CR>",
            --- table: next field; empty headline / item: cycle its level
            insert_tab = "<Tab>",
            table_prev_field = "<S-Tab>",
            table_next_row = "<CR>",
            table_copy_down = "<S-CR>",
          },
          --- Emacs Org keys (org-mode-map), on top of the Vim-style keys above.
          --- Set a section to `false` to disable it, or an entry to `false` to
          --- drop one key.
          emacs_global = {
            agenda = "<C-c>a",
            capture = "<C-c>c",
            store_link = "<C-c>l",
          },
          emacs = {
            -- structure
            insert_heading = "<C-CR>",
            insert_todo_heading = "<C-S-CR>",
            ctrl_c_ret = "<C-c><CR>",
            ctrl_c_star = "<C-c>*",
            table_recalc_buffer = false, -- also C-u C-u C-c * in a table
            ctrl_c_minus = "<C-c>-",
            ctrl_c_caret = "<C-c>^",
            toggle_comment = "<C-c>;",
            insert_structure_template = "<C-c><C-,>",
            insert_drawer = "<C-c><C-x>d",
            insert_footnote = "<C-c><C-x>f",
            emphasize = "<C-c><C-x><C-f>",
            clone_subtree = "<C-c><C-x>c",
            copy_special = "<C-c><C-x><M-w>",
            cut_special = "<C-c><C-x><C-w>",
            paste_special = "<C-c><C-x><C-y>",
            mark_subtree = "<C-c>@",
            indirect_subtree = "<C-c><C-x>b",
            -- elements (M-h org-mark-element is taken by meta_left)
            forward_element = "<M-}>",
            backward_element = "<M-{>",
            up_element = "<C-c><C-^>",
            down_element = "<C-c><C-_>",
            transpose_element = "<C-M-t>",
            next_block = "<C-c><M-f>",
            previous_block = "<C-c><M-b>",
            toggle_fixed_width = "<C-c>:",
            list_make_subtree = "<C-c><C-*>",
            toggle_radio_button = "<C-c><C-x><C-r>",
            toggle_pretty_entities = "<C-c><C-x>\\",
            inlinetask_insert = "<C-c><C-x>t",
            -- visibility
            show_branches = "<C-c><C-k>",
            show_children = "<C-c><Tab>",
            reveal = "<C-c><C-r>",
            force_cycle_archived = "<C-c><C-Tab>",
            copy_visible = "<C-c><C-x>v",
            -- motion
            next_heading = "<C-c><C-n>",
            prev_heading = "<C-c><C-p>",
            next_sibling = "<C-c><C-f>",
            prev_sibling = "<C-c><C-b>",
            goto_parent = "<C-c><C-u>",
            buffer_goto = "<C-c><C-j>",
            -- todo / priority / tags / properties
            todo = "<C-c><C-t>",
            todo_next_sequence = "<C-S-Right>",
            todo_prev_sequence = "<C-S-Left>",
            priority = "<C-c>,",
            set_tags = "<C-c><C-q>",
            set_property = "<C-c><C-x>p",
            set_property_and_value = "<C-c><C-x>P",
            toggle_tags_groups = "<C-c><C-x>q",
            toggle_ordered = "<C-c><C-x>o",
            add_note = "<C-c><C-z>",
            -- dates
            schedule = "<C-c><C-s>",
            deadline = "<C-c><C-d>",
            timestamp = "<C-c>.",
            timestamp_inactive = "<C-c>!",
            toggle_time_stamp_overlays = "<C-c><C-x><C-t>",
            date_today = "<C-c><",
            goto_calendar = "<C-c>>",
            evaluate_time_range = "<C-c><C-y>",
            -- lists
            toggle_checkbox = "<C-c><C-x><C-b>",
            update_statistics = "<C-c>#",
            -- clock / effort / dynamic blocks
            clock_in = { "<C-c><C-x><C-i>", "<C-c><C-x><Tab>" },
            clock_in_last = "<C-c><C-x><C-x>",
            clock_out = "<C-c><C-x><C-o>",
            clock_cancel = "<C-c><C-x><C-q>",
            clock_goto = "<C-c><C-x><C-j>",
            clock_report = "<C-c><C-x><C-r>",
            clock_display = "<C-c><C-x><C-d>",
            link_preview = "<C-c><C-x><C-v>",
            link_preview_refresh = "<C-c><C-x><C-M-v>",
            latex_preview = "<C-c><C-x><C-l>",
            set_effort = "<C-c><C-x>e",
            inc_effort = "<C-c><C-x>E",
            clock_modify_effort = "<C-c><C-x><C-e>",
            clock_resolve = "<C-c><C-x><C-z>",
            shift_control_up = "<C-S-Up>",
            shift_control_down = "<C-S-Down>",
            dblock_update = "<C-c><C-x><C-u>",
            column_view = "<C-c><C-x><C-c>",
            insert_columnview = "<C-c><C-x>i",
            insert_dblock = "<C-c><C-x>x",
            -- timers
            timer_start = "<C-c><C-x>0",
            timer_stop = "<C-c><C-x>_",
            timer_pause = "<C-c><C-x>,",
            timer_insert = "<C-c><C-x>.",
            timer_item = "<C-c><C-x>-",
            timer_countdown = "<C-c><C-x>;",
            -- links
            insert_link = "<C-c><C-l>",
            open_link_or_entry = "<C-c><C-o>",
            insert_last_stored_link = "<C-c><M-l>",
            insert_all_links = "<C-c><C-M-l>",
            mark_ring_goto = "<C-c>&",
            next_link = "<C-c><C-x><C-n>",
            prev_link = "<C-c><C-x><C-p>",
            -- refile / archive / attach / agenda files
            refile = "<C-c><C-w>",
            refile_copy = "<C-c><M-w>",
            archive_subtree = { "<C-c>$", "<C-c><C-x><C-s>", "<C-c><C-x><C-a>" },
            toggle_archive_tag = "<C-c><C-x>a",
            archive_to_sibling = "<C-c><C-x>A",
            attach = "<C-c><C-a>",
            agenda_file_to_front = "<C-c>[",
            agenda_file_remove = "<C-c>]",
            cycle_agenda_files = { "<C-'>", "<C-,>" },
            agenda_set_restriction_lock = "<C-c><C-x><",
            agenda_remove_restriction_lock = "<C-c><C-x>>",
            -- search / export / special
            sparse_tree = "<C-c>/",
            tags_sparse_tree = "<C-c>\\",
            export = "<C-c><C-e>",
            edit_special = "<C-c>'",
            -- tables
            table_create = "<C-c>|",
            table_formula = "<C-c>=",
            table_edit_field = "<C-c>`",
            table_sum = "<C-c>+",
            table_blank_field = "<C-c><Space>",
            table_coordinates = "<C-c>}",
            table_field_info = "<C-c>?",
            table_rotate_marks = "<C-#>",
            table_formula_debugger = "<C-c>{",
            table_ascii_plot = '<C-c>"a',
            table_plot = '<C-c>"g',
            table_el = "<C-c>~",
            -- babel (C-c C-v)
            babel_execute = { "<C-c><C-v>e", "<C-c><C-v><C-e>" },
            babel_execute_buffer = { "<C-c><C-v>b", "<C-c><C-v><C-b>" },
            babel_execute_subtree = { "<C-c><C-v>s", "<C-c><C-v><C-s>" },
            babel_tangle = { "<C-c><C-v>t", "<C-c><C-v><C-t>" },
            babel_remove_result = "<C-c><C-v>k",
            babel_next_block = { "<C-c><C-v>n", "<C-c><C-v><C-n>" },
            babel_prev_block = { "<C-c><C-v>p", "<C-c><C-v><C-p>" },
            babel_tangle_file = { "<C-c><C-v>f", "<C-c><C-v><C-f>" },
            babel_expand = { "<C-c><C-v>v", "<C-c><C-v><C-v>" },
            babel_view_info = "<C-c><C-v>I",
            babel_check = { "<C-c><C-v>c", "<C-c><C-v><C-c>" },
            babel_insert_header_arg = { "<C-c><C-v>j", "<C-c><C-v><C-j>" },
            babel_goto_named = "<C-c><C-v>g",
            babel_goto_named_result = { "<C-c><C-v>r", "<C-c><C-v><C-r>" },
            babel_goto_head = { "<C-c><C-v>u", "<C-c><C-v><C-u>" },
            babel_open_result = { "<C-c><C-v>o", "<C-c><C-v><C-o>" },
            babel_demarcate = { "<C-c><C-v>d", "<C-c><C-v><C-d>" },
            babel_lob_ingest = { "<C-c><C-v>i", "<C-c><C-v><Tab>" },
            babel_load_in_session = { "<C-c><C-v>l", "<C-c><C-v><C-l>" },
            babel_switch_to_session = "<C-c><C-v><C-z>",
            babel_switch_to_session_with_code = "<C-c><C-v>z",
            babel_sha1_hash = { "<C-c><C-v>a", "<C-c><C-v><C-a>" },
            babel_describe_bindings = "<C-c><C-v>h",
            babel_mark_block = "<C-c><C-v><C-M-h>",
            babel_do_key_sequence = { "<C-c><C-v>x", "<C-c><C-v><C-x>" },
          },
          --- Insert-mode Emacs keys.
          emacs_insert = {
            insert_heading = "<C-CR>",
            insert_todo_heading = "<C-S-CR>",
          },
          text_objects = {
            inner_heading = "ih",
            around_heading = "ah",
            inner_subtree = "ir",
            around_subtree = "ar",
          },
          agenda = {
            quit = "q",
            quit_kill = "Q",
            exit = "x",
            redo = "r",
            redo_all = "gr", -- Emacs: g (a Vim prefix key)
            later = "f",
            earlier = "b",
            today = ".",
            goto_date = "gd", -- Emacs: j (kept free for motion)
            day_view = "vd",
            week_view = "vw",
            fortnight_view = "vt",
            month_view = "vm",
            year_view = "vy",
            reset_view = "v<Space>",
            -- goto = "<TAB>",
            switch_to = "<CR>",
            show = "<Space>",
            show_scroll_down = "<BS>",
            recenter = "L",
            delete_other_windows = "o",
            follow_mode = { "F", "vf" },
            todo = { "t", "<C-c><C-t>" },
            todo_next = "<C-S-Right>",
            todo_prev = "<C-S-Left>",
            priority = { ",", "<C-c>," },
            priority_up = { "+", "<S-Up>" },
            priority_down = { "-", "<S-Down>" },
            set_tags = { ":", "<C-c><C-q>", "<C-c><C-c>" },
            show_tags = "T",
            set_property = "<C-c><C-x>p",
            schedule = { "<C-c><C-s>", "s" },
            deadline = { "<C-c><C-d>", "d" },
            date_later = { "<S-Right>", "<C-c><C-x><Right>" },
            date_earlier = { "<S-Left>", "<C-c><C-x><Left>" },
            date_prompt = ">",
            clock_in = { "I", "<C-c><C-x><C-i>" },
            clock_out = { "O", "<C-c><C-x><C-o>" },
            clock_cancel = { "X", "<C-c><C-x><C-x>" },
            clock_goto = { "J", "<C-c><C-x><C-j>" },
            attach = "<C-c><C-a>",
            set_effort = { "e", "<C-c><C-x>e" },
            timer = ";",
            timer_stop = "<C-c><C-x>_",
            restriction_lock = "<C-c><C-x><",
            remove_restriction_lock = "<C-c><C-x>>",
            refile = { "<C-c><C-w>", "R" },
            archive = { "$", "<C-c>$", "<C-c><C-x><C-s>" },
            archive_default = { "a", "<C-c><C-x><C-a>" },
            archive_sibling = "<C-c><C-x>A",
            toggle_archive_tag = "<C-c><C-x>a",
            kill = "<C-k>",
            open_link = "<C-c><C-o>",
            add_note = { "z", "<C-c><C-z>" },
            log_mode = { "l", "vl" },
            log_all_mode = "vL",
            clockcheck_mode = "vc",
            clockreport_mode = { "C", "vR" },
            entry_text_mode = { "E", "vE" },
            archives_mode = "va",
            archives_files_mode = "vA",
            inactive_mode = "v[",
            time_grid = { "G", "vG" },
            toggle_deadlines = { "!", "v!" },
            dim_blocked = "#",
            filter = "/",
            filter_tag = "\\",
            filter_category = "<",
            filter_regexp = "=",
            filter_effort = "_",
            filter_top_headline = "^",
            filter_remove = "|",
            limit = "~",
            query_add = "[",
            query_subtract = "]",
            query_add_re = "{",
            query_subtract_re = "}",
            mark = "m",
            unmark = "u",
            unmark_all = "U",
            toggle_mark = "<M-m>",
            mark_all = "*",
            toggle_mark_all = "<M-*>",
            mark_regexp = "%",
            bulk_action = "B",
            next_item = "n",
            prev_item = "p",
            next_date_line = "<C-c><C-n>",
            prev_date_line = "<C-c><C-p>",
            forward_block = "<C-Down>",
            backward_block = "<C-Up>",
            drag_line_forward = "<M-Down>",
            drag_line_backward = "<M-Up>",
            append = "A",
            columns = "<C-c><C-x><C-c>",
            calendar = "c",
            save_all = "<C-x><C-s>",
            capture = "K", -- Emacs: k (kept free for motion)
            export = "<C-x><C-w>",
            help = "g?",
          },
          capture = {
            finalize = { "<C-c><C-c>", "<prefix>w" },
            kill = { "<Leader>bk", "<prefix>k", "q" },
            refile = { "R", "<prefix>r" },
          },
          edit_src = {
            save_exit = { "<C-c>'", "<prefix>'" },
            abort = { "<C-c><C-k>", "<prefix>k" },
          },
        },
      }
    end,
  },
})
