# yazi.toml
[manager]
show_hidden = true
ratio = [0, 3, 0]     # set 0 - remove view panel
sort_dir_first = true

play = [{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" }]

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
  { run = 'code "%*"', orphan = true, for = "windows" },
]

# [open]
# rules = [{ mime = "video/*", use = ["play", "reveal"] }]
