# yazi.toml
[manager]
show_hidden = true
ratio = [0, 3, 0] # set 0 - remove view panel
sort_dir_first = true

[opener]
edit = [
	{ exec = '$EDITOR "$@"', block = true,  for = "unix" },
	{ exec = 'code "%*"',    orphan = true, for = "windows" },
]
# play = [
# 	{ run = 'mpv "$@"', orphan = true, for = "unix" },
# ]
# open = [
# 	{ run = 'xdg-open "$@"', desc = "Open" },
# ]
