# yazi.toml
[mgr]
show_hidden = true
ratio = [0, 3, 0]     # set 0 - remove view panel
sort_dir_first = true
sort_by = "natural"

play = [{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" }]

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
  { run = 'code "%*"', orphan = true, for = "windows" },
]

[plugin]
fetchers = [
	# plugins - git.yazi
	{ id = "git", name = "*", run = "git"},
	{ id = "git", name = "*/", run = "git"},
]
