#!/bin/bash

set -u -e

LC_TIME=id_ID.UTF-8

_notifysend() {
  COL_MSG_SUCCESS="$(xrdb -query | grep "color3" | head -n 1 | cut -d":" -f2 | xargs)"
}

_maimselection() {
  _notifysend
  maim --select --hidecursor --quiet "$IMGTEMP/$NAME_FILE"

  MSG_SCROT="<b><span foreground='$COL_MSG_SUCCESS'>SUCCESS !!</span></b>\n$NAME_FILE"

  dunstify "Take a screenshot:" "$MSG_SCROT"
  sleep 1

  case "$XDG_SESSION_DESKTOP" in
  "bspwm") bspc rule -a \* -o state=floating && sxiv "$IMGTEMP/$NAME_FILE" ;;
  *) sxiv "$IMGTEMP/$NAME_FILE" ;;
  esac

  dunstify "Path save:" "<b><span foreground='$COL_MSG_SUCCESS'>$IMGTEMP/$NAME_FILE</span></b>"
}

_maimfullscreen() {
  _notifysend
  maim --hidecursor --quiet "$IMGTEMP/$NAME_FILE"

  MSG_SCROT="<b><span foreground='$COL_MSG_SUCCESS'>SUCCESS !!</span></b>\n$NAME_FILE"

  dunstify "Take a screenshot:" "$MSG_SCROT"
  sleep 1

  case "$XDG_SESSION_DESKTOP" in
  "bspwm") bspc rule -a \* -o state=floating && sxiv "$IMGTEMP/$NAME_FILE" ;;
  *) sxiv "$IMGTEMP/$NAME_FILE" ;;
  esac

  dunstify "Path save:" "<b><span foreground='$COL_MSG_SUCCESS'>$IMGTEMP/$NAME_FILE</span></b>"
}

# Main script

(
  NAME_PATH_PNG="$(date '+%y%m%d-%H-%M-%S')"
  NAME_FILE="screenshot-$NAME_PATH_PNG.png"
  IMGTEMP="$HOME/Downloads/screenshot"

  dir="$HOME/.config/rofi/menu"
  theme="styles/menuleft"
  rofi_command="rofi -theme $dir/$theme"

  mkdir -p "$IMGTEMP"
  mkdir -p "$IMGTEMP/videos"

  options="selection\nfullscreen\n"
  chosen="$(echo -e "$options" | $rofi_command -p "  " -dmenu -i)"

  [[ -z "$chosen" ]] && exit

  case "$chosen" in
  "selection") _maimselection ;;
  "fullscreen") _maimfullscreen ;;
  *) dunstify "takescreenshot:" "aborting.." ;;
  esac
)
