EnableImagePreviewing: false
themes:
  - name: "ashen"
    colors:
      - "#121212"
      - "#121212"
      - "#B14242"
      - "#949494"
      - "#B14242"
      - "#D87C4A"
      - "#E49A44"
      - "#4A8B8B"
      - "#d5d5d5"
  - name: "base46-chocolate"
    colors:
      - "#2f2c2b"
      - "#393635"
      - "#c65f5f"
      - "#dc7575"
      - "#8ca589"
      - "#95ae92"
      - "#d9b27c"
      - "#e1ba84"
      - "#7d92a2"
      - "#728797"
      - "#b48ead"
      - "#b48ead"
      - "#829e9b"
      - "#749689"
      - "#e5e9f0"
      - "#eceff4"
  - name: "vscode_modern"
    colors:
      - "#cccccc"
      - "#1f1f1f"
      - "#1e1e1e"
      - "#dcdcaa"
      - "#569cd6"
      - "#c678dd"
      - "#56b6c2"
      - "#d4d4d4"
      - "#808080"
      - "#dcdcaa"
      - "#569cd6"
      - "#c678dd"
      - "#56b6c2"
      - "#d4d4d4"
  - name: "base46-aylin"
    colors:
      - "#363b46"
      - "#3c424e"
      - "#FD98B9"
      - "#f45c7f"
      - "#9fd54d"
      - "#addb67"
      - "#becf00"
      - "#ebff00"
      - "#6cbeff"
      - "#d9b6f0"
      - "#FD98B9"
      - "#7fdbca"
      - "#7fdbca"
      - "#C7C7C7"
      - "#FEFFFF"
      - "#9fd4ff"
  - name: "base46-default-dark"
    colors:
      - "#d8d8d8"
      - "#181818"
      - "#2d2d2d"
      - "#343434"
      - "#ab4642"
      - "#a16946"
      - "#a1b56c"
      - "#abcb56"
      - "#f7ca88"
      - "#f8ce92"
      - "#7cafc2"
      - "#609eb5"
      - "#ba8baf"
      - "#a86c9a"
      - "#6cb598"
      - "#86c1b9"
      - "#C7C7C7"
      - "#FEFFFF"
  - name: "base46-doomchad"
    colors:
      - "#32363e"
      - "#3c4048"
      - "#ff6b5a"
      - "#ff7665"
      - "#98be65"
      - "#a9cf76"
      - "#ECBE7B"
      - "#f2c481"
      - "#dc8ef3"
      - "#c678dd"
      - "#47a5e5"
      - "#51afef"
      - "#4db5bd"
      - "#46D9FF"
      - "#C7C7C7"
      - "#FEFFFF"
      - "#a86ec9"
  - name: "base46-jabuti"
    colors:
      - "#292a37"
      - "#343545"
      - "#3c3e51"
      - "#ec6a88"
      - "#ff8cbe"
      - "#3FDAA4"
      - "#08bdba"
      - "#e1c697"
      - "#E8D4B0"
      - "#78a9ff"
      - "#78a9ff"
      - "#be95ff"
  - name: "base46-jellybeans"
    colors:
      - "#dedede"
      - "#121212"
      - "#929292"
      - "#bdbdbd"
      - "#be95ff"
      - "#be95ff"
      - "#94b979"
      - "#bddeab"
      - "#ffba7b"
      - "#ffdca0"
      - "#97bedc"
      - "#b1d8f6"
      - "#e1c0fa"
      - "#fbdaff"
      - "#00988e"
      - "#1ab2a8"
      - "#dedede"
      - "#ffffff"
  - name: "base46-kanagawa"
    colors:
      - "#c8c3a6"
      - "#1f1f28"
      - "#272730"
      - "#2f2f38"
      - "#d8616b"
      - "#e46876"
      - "#98BB6C"
      - "#a3c677"
  - name: "base46-material-darker"
    colors:
      - "#303030"
      - "#383838"
      - "#f07178"
      - "#ff5370"
      - "#c3e88d"
      - "#c3e88d"
      - "#ffcb6b"
      - "#ffcb6b"
      - "#6e98eb"
      - "#82aaff"
      - "#c792ea"
      - "#b480d6"
      - "#89ddff"
      - "#6e98eb"
      - "#ffffff"
      - "#ffffff"
  - name: "base46-onenord"
    colors:
      - "#3B4252"
      - "#4C566A"
      - "#E06C75"
      - "#E06C75"
      - "#9EC183"
      - "#9EC183"
      - "#EBCB8B"
      - "#EBCB8B"
      - "#81A1C1"
      - "#81A1C1"
      - "#B988B0"
      - "#B988B0"
      - "#88C0D0"
      - "#8FBCBB"
      - "#E5E9F0"
      - "#ECEFF4"
  - name: "base46-seoul256_dark"
    colors:
      - "#585858"
      - "#5f5f5f"
      - "#719672"
      - "#97bb98"
      - "#e0bb71"
      - "#ffdd98"
      - "#96BBDC"
      - "#BADCFC"
      - "#DFBDBC"
      - "#FFBEB0"
      - "#96DDDE"
      - "#96ddde"
      - "#d8d8d8"
      - "#e9e9e9"
      - "#dfbdbc"
  - name: "base46-solarized_dark"
    colors:
      - "#002831"
      - "#475b62"
      - "#d11c24"
      - "#bd3613"
      - "#738a05"
      - "#475b62"
      - "#a57706"
      - "#536870"
      - "#2176c7"
      - "#708284"
      - "#c61c6f"
      - "#5956ba"
      - "#259286"
      - "#819090"
      - "#eae3cb"
      - "#fcf4dc"
  - name: "base46-zenburn"
    colors:
      - "#464646"
      - "#4d4d4d"
      - "#e3716e"
      - "#ec8685"
      - "#5f7f5f"
      - "#5f7f5f"
      - "#b77e64"
      - "#d68c67"
      - "#7cb8bb"
      - "#93e0e3"
      - "#b279a7"
      - "#cf86c1"
      - "#93e0e3"
      - "#93e0e3"
      - "#f0e4cf"
      - "#c0ab86"
  - name: "catppuccin-mocha"
    colors:
      - "#45475A"
      - "#585B70"
      - "#A6E3A1"
      - "#A6E3A1"
      - "#F9E2AF"
      - "#F9E2AF"
      - "#89B4FA"
      - "#89B4FA"
      - "#F5C2E7"
      - "#F5C2E7"
      - "#94E2D5"
      - "#94E2D5"
      - "#BAC2DE"
      - "#A6ADC8"
  - name: "darkearth"
    colors:
      - "#24211E"
      - "#24211E"
      - "#5F865F"
      - "#5F865F"
      - "#77824A"
      - "#77824A"
      - "#77824a"
      - "#B36B42"
      - "#BB7844"
      - "#BB7844"
      - "#C9A654"
      - "#C9A654"
      - "#D7C484"
      - "#D7C484"
  - name: "horizon"
    colors:
      - "#131419"
      - "#676767"
      - "#29D398"
      - "#3FDAA4"
      - "#FAB795"
      - "#FBC3A7"
      - "#26BBD9"
      - "#3FC6DE"
      - "#EE64AE"
      - "#F075B7"
      - "#59E3E3"
      - "#6BE6E6"
      - "#C7C7C7"
      - "#FEFFFF"
  - name: "lackluster"
    colors:
      - "#080808"
      - "#d70000"
      - "#789978"
      - "#ffaa88"
      - "#7788aa"
      - "#d7007d"
      - "#708090"
      - "#deeeed"
      - "#444444"
      - "#789978"
      - "#ffaa88"
      - "#7788aa"
      - "#d7007d"
      - "#708090"
      - "#deeeed"
  - name: "oxocarbon"
    colors:
      - "#161616"
      - "#585858"
      - "#3ddbd9"
      - "#3ddbd9"
      - "#33b1ff"
      - "#33b1ff"
      - "#be95ff"
      - "#be95ff"
      - "#ff7eb6"
      - "#ff7eb6"
      - "#f2f4f8"
      - "#f2f4f8"
  - name: "rose-pine-dawn"
    colors:
      - "#f2e9e1"
      - "#9893a5"
      - "#286983"
      - "#286983"
      - "#ea9d34"
      - "#ea9d34"
      - "#56949f"
      - "#56949f"
      - "#907aa9"
      - "#907aa9"
      - "#d7827e"
      - "#d7827e"
      - "#575279"
      - "#575279"
  - name: "rose-pine-main"
    colors:
      - "#26233a"
      - "#6e6a86"
      - "#eb6f92"
      - "#eb6f92"
      - "#31748f"
      - "#31748f"
      - "#f6c177"
      - "#f6c177"
      - "#9ccfd8"
      - "#9ccfd8"
      - "#c4a7e7"
      - "#c4a7e7"
      - "#ebbcba"
      - "#ebbcba"
      - "#e0def4"
      - "#e0def4"
  - name: "tokyonight-night"
    colors:
      - "#15161e"
      - "#1a1b26"
      - "#7aa2f7"
      - "#bb9af7"
      - "#7dcfff"
      - "#a9b1d6"
      - "#414868"
      - "#e0af68"
      - "#7aa2f7"
      - "#bb9af7"
      - "#7dcfff"
      - "#c0caf5"
  - name: "tokyonight-storm"
    colors:
      - "#1d202f"
      - "#7aa2f7"
      - "#bb9af7"
      - "#7dcfff"
      - "#a9b1d6"
      - "#414868"
      - "#7aa2f7"
      - "#bb9af7"
      - "#7dcfff"
      - "#c0caf5"
