EnableImagePreviewing: false
themes:
  - name: "ashen"
    colors:
      - "#121212"
      - "#121212"
      - "#B14242"
      - "#B14242"
      - "#B14242"
      - "#D87C4A"
      - "#E49A44"
      - "#4A8B8B"
      - "#d5d5d5"
  - name: "base46-aylin"
    colors:
      - "#24262e"
      - "#3c424e"
      - "#9fd4ff"
      - "#6cbeff"
      - "#9fd4ff"
      - "#6cbeff"
      - "#9fd4ff"
      - "#6cbeff"
      - "#9fd4ff"
      - "#6cbeff"
      - "#7fdbca"
      - "#7fdbca"
      - "#C7C7C7"
      - "#FEFFFF"
  - name: "base46-catppuccin"
    colors:
      - "#1e1e2e"
      - "#45475A"
      - "#585B70"
      - "#89B4FA"
      - "#89B4FA"
      - "#89B4FA"
      - "#89B4FA"
      - "#F5C2E7"
      - "#F5C2E7"
      - "#94E2D5"
      - "#94E2D5"
      - "#BAC2DE"
      - "#A6ADC8"
  - name: "base46-chocolate"
    colors:
      - "#2f2c2b"
      - "#393635"
      - "#c65f5f"
      - "#dc7575"
      - "#d9b27c"
      - "#e1ba84"
      - "#7d92a2"
      - "#728797"
  - name: "base46-doomchad"
    colors:
      - "#282c34"
      - "#3c4048"
      - "#47a5e5"
      - "#51afef"
      - "#4db5bd"
      - "#46D9FF"
      - "#ECBE7B"
      - "#f2c481"
      - "#dc8ef3"
      - "#c678dd"
      - "#47a5e5"
      - "#51afef"
      - "#4db5bd"
      - "#46D9FF"
      - "#C7C7C7"
      - "#FEFFFF"
      - "#a86ec9"
  - name: "base46-everforest"
    colors:
      - "#2b3339"
      - "#7a8478"
      - "#e67e80"
      - "#a7c080"
      - "#dbbc7f"
      - "#7fbbb3"
      - "#d699b6"
      - "#83c092"
      - "#f2efdf"
      - "#a6b0a0"
      - "#f85552"
      - "#8da101"
      - "#dfa000"
      - "#3a94c5"
      - "#df69ba"
      - "#35a77c"
      - "#fffbef"
  - name: "base46-gruvchad"
    colors:
      - "#282828"
      - "#cc241d"
      - "#98971a"
      - "#d79921"
      - "#458588"
      - "#b16286"
      - "#689d6a"
      - "#a89984"
      - "#928374"
      - "#fb4934"
      - "#b8bb26"
      - "#fabd2f"
      - "#83a598"
      - "#d3869b"
      - "#8ec07c"
      - "#ebdbb2"
  - name: "base46-horizon"
    colors:
      - "#1d1f27"
      # - "#1c1e26"
      - "#29D398"
      - "#3FDAA4"
      - "#FAB795"
      - "#FBC3A7"
      - "#26BBD9"
      # - "#3FC6DE"
      # - "#EE64AE"
      # - "#F075B7"
      # - "#59E3E3"
      # - "#6BE6E6"
      - "#C7C7C7"
      - "#FEFFFF"
  - name: "base46-jabuti"
    colors:
      - "#292a37"
      - "#3c3e51"
      - "#78a9ff"
      - "#78a9ff"
      - "#3FDAA4"
      - "#08bdba"
      - "#e1c697"
      - "#E8D4B0"
      - "#78a9ff"
      - "#78a9ff"
      - "#be95ff"
      - "#936FDC"
      - "#6be6e6"
      - "#09deda"
      - "#e5e9f0"
      - "#eceff4"
  - name: "base46-jellybeans"
    colors:
      - "#151515"
      - "#121212"
      - "#929292"
      # - "#bdbdbd"
      # - "#be95ff"
      # - "#be95ff"
      # - "#94b979"
      # - "#bddeab"
      # - "#ffba7b"
      # - "#ffdca0"
      - "#97bedc"
      # - "#b1d8f6"
      # - "#e1c0fa"
      # - "#fbdaff"
      # - "#00988e"
      # - "#1ab2a8"
      - "#dedede"
      - "#ffffff"
  - name: "base46-kanagawa"
    colors:
      - "#1f1f28"
      - "#2f2f38"
      - "#d8616b"
      - "#e46876"
      - "#98BB6C"
      - "#a3c677"
      - "#FF9E3B"
      - "#FFA066"
      - "#7E9CD8"
      - "#7FB4CA"
      - "#a48ec7"
      - "#9c86bf"
      - "#A3D4D5"
      - "#7AA89F"
      - "#c8c093"
      - "#c5c9c5"
  - name: "base46-material-darker"
    colors:
      - "#212121"
      - "#383838"
      - "#6e98eb"
      - "#82aaff"
      - "#c3e88d"
      - "#c3e88d"
      - "#6e98eb"
      - "#82aaff"
      - "#6e98eb"
      - "#82aaff"
      - "#c792ea"
      - "#b480d6"
      - "#89ddff"
      - "#6e98eb"
      - "#ffffff"
      - "#ffffff"
  - name: "base46-melange"
    colors:
      - "#34302c"
      - "#867462"
      - "#bd8183"
      - "#d47766"
      - "#78997a"
      - "#85b695"
      - "#e49b5d"
      - "#ebc06d"
      - "#7f91b2"
      - "#a3a9ce"
      - "#b380b0"
      - "#cf9bc2"
      - "#7b9695"
      - "#89b3b6"
      - "#c1a78e"
      - "#ece1d7"
  - name: "base46-onenord"
    colors:
      - "#2a303c"
      - "#4C566A"
      - "#EBCB8B"
      - "#EBCB8B"
      - "#81A1C1"
      - "#81A1C1"
      - "#B988B0"
      - "#B988B0"
      - "#88C0D0"
      - "#8FBCBB"
      - "#E5E9F0"
      - "#ECEFF4"
  - name: "base46-oxocarbon"
    colors:
      - "#161616"
      - "#585858"
      - "#3ddbd9"
      - "#3ddbd9"
      - "#33b1ff"
      - "#33b1ff"
      # - "#be95ff"
      # - "#be95ff"
      # - "#f2f4f8"
      - "#161616"
      - "#f2f4f8"
  - name: "base46-rosepine"
    colors:
      - "#191724"
      - "#6e6a86"
      - "#31748f"
      - "#31748f"
      - "#31748f"
      - "#31748f"
      - "#31748f"
      - "#31748f"
      - "#9ccfd8"
      - "#9ccfd8"
      - "#c4a7e7"
      - "#c4a7e7"
      - "#ebbcba"
      - "#ebbcba"
      - "#e0def4"
      - "#e0def4"
  - name: "base46-seoul256_dark"
    colors:
      - "#585858"
      - "#5f5f5f"
      - "#df9a98"
      - "#FFBEB0"
      - "#719672"
      - "#97bb98"
      - "#e0bb71"
      - "#ffdd98"
      - "#96BBDC"
      - "#BADCFC"
      - "#DFBDBC"
      - "#FFBEB0"
      - "#96DDDE"
      - "#96ddde"
      - "#d8d8d8"
      - "#e9e9e9"
  - name: "base46-solarized_dark"
    colors:
      # - "#1e1e2e"
      - "#002b36"
      - "#002831"
      # - "#475b62"
      # - "#d11c24"
      # - "#bd3613"
      # - "#738a05"
      # - "#475b62"
      # - "#a57706"
      # - "#536870"
      # - "#2176c7"
      # - "#708284"
      # - "#c61c6f"
      - "#5956ba"
      # - "#259286"
      - "#002831"
      # - "#819090"
      # - "#eae3cb"
      # - "#fcf4dc"
  - name: "base46-vscode_dark"
    colors:
      - "#414453"
      - "#ff8170"
      - "#78c2b3"
      - "#d9c97c"
      - "#4eb0cc"
      - "#ff7ab2"
      - "#b281eb"
      - "#dfdfe0"
      - "#7f8c98"
      - "#ff8170"
      - "#acf2e4"
      - "#ffa14f"
      - "#6bdfff"
      - "#ff7ab2"
      - "#dabaff"
      - "#dfdfe0"
  - name: "base46-wombat"
    colors:
      - "#202020"
      - "#313131"
      - "#ff615a"
      - "#f58c80"
      - "#b1e969"
      - "#ddf88f"
      - "#ebd99c"
      - "#eee5b2"
      - "#5da9f6"
      - "#a5c7ff"
      - "#e86aff"
      - "#ddaaff"
      - "#82fff7"
      - "#b7fff9"
      - "#dedacf"
      - "#ffffff"
  - name: "base46-zenburn"
    colors:
      - "#464646"
      - "#4d4d4d"
      # - "#e3716e"
      # - "#ec8685"
      # - "#5f7f5f"
      # - "#5f7f5f"
      # - "#b77e64"
      # - "#d68c67"
      # - "#7cb8bb"
      # - "#93e0e3"
      - "#b279a7"
      - "#cf86c1"
      - "#93e0e3"
      - "#93e0e3"
      - "#f0e4cf"
      - "#c0ab86"
  - name: "kanso-ink"
    colors:
      - "#14171d"
      - "#c4746e"
      # - "#8a9a7b"
      # - "#c4b28a"
      # - "#8ba4b0"
      # - "#a292a3"
      # - "#8ea4a2"
      # - "#c8c093"
      # - "#a4a7a4"
      # - "#e46876"
      # - "#87a987"
      # - "#e6c384"
      - "#7fb4ca"
      - "#938aa9"
      - "#7aa89f"
      - "#c5c9c7"
  - name: "lackluster"
    colors:
      - "#101010"
      - "#080808"
      - "#444444"
      - "#444444"
      - "#deeeed"
  - name: "rose-pine-dawn"
    colors:
      # - "#56949f"
      # - "#907aa9"
      # - "#907aa9"
      - "#faf4ed"
      # - "#bec0c8"
      - "#56949f"
      # - "#575279"
      - "#575279"
      - "#faf4ed"
  - name: "tokyonight-night"
    colors:
      - "#15161e"
      - "#1a1b26"
      - "#7aa2f7"
      - "#bb9af7"
      - "#7dcfff"
      - "#a9b1d6"
      - "#414868"
      - "#7aa2f7"
      - "#7aa2f7"
      - "#bb9af7"
      - "#7dcfff"
      - "#c0caf5"
  - name: "tokyonight-storm"
    colors:
      - "#24283b"
      - "#7aa2f7"
      - "#bb9af7"
      - "#7dcfff"
      - "#a9b1d6"
      - "#414868"
      - "#7aa2f7"
      - "#bb9af7"
      - "#7dcfff"
      - "#c0caf5"
  - name: "vscode_modern"
    colors:
      - "#cccccc"
      - "#1f1f1f"
      - "#1e1e1e"
      - "#1f1f1f"
      - "#1e1e1e"
      - "#1f1f1f"
      - "#1e1e1e"
      - "#d4d4d4"
      - "#808080"
      - "#dcdcaa"
      - "#569cd6"
      - "#c678dd"
      - "#56b6c2"
      - "#d4d4d4"
