# Catppuccin Mocha for Kitty
foreground   #cdd6f4
background   #1e1e2e
cursor       #f5e0dc

# Normal
color0  #1e1e2e
color1  #ef596f
color2  #a6e3a1
color3  #f9e2af
color4  #89b4fa
color5  #f5c2e7
color6  #94e2d5
color7  #cdd6f4

# Bright
color8  #45475a
color9  #ef596f
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #f5c2e7
color14 #94e2d5
color15 #f5e0dc

# Cursor
cursor_text_color   #1e1e2e

active_border_color   #2d2d45
inactive_border_color #242437
bell_border_color       #F9E2AF

# Tabs
active_tab_background   #4e4e78
active_tab_foreground   #1e1e2e
inactive_tab_background #1e1e2e
inactive_tab_background #1e1e2e
tab_bar_background      #1e1e2e
