
color0 #141617
color1 #ea6926
color2 #c1d041
color3 #eecf75
color4 #cd5f59
color5 #fd9bc1
color6 #fe9d6e
color7 #ffffff
color8 #4c4c4c
color9 #d3573b
color10 #c1d041
color11 #eecf75
color12 #2c86ff
color13 #fd9bc1
color14 #92a5df
color15 #ffffff

background #101010
foreground #d4be98

cursor #fe9d6e
cursor_text_color #000000


selection_foreground #1d2021
selection_background #d4be98

underline_color #97c8f7
url_color #97c8f7

# Kitty window border colors
active_border_color #1c1c1c
inactive_border_color #131313
bell_border_color       #F9E2AF

# Tabs
active_tab_background #291614
active_tab_foreground #633028
inactive_tab_background #383838
inactive_tab_background #383838
tab_bar_background #101010
