
# --- Hubbamax Color Scheme ---

background #1c1c1c
foreground #d0d0d0
cursor     #d0d0d0

color0  #1c1c1c
color1  #af5f5f
color2  #5f875f
color3  #87875f
color4  #5f87af
color5  #875f87
color6  #5f8787
color7  #d0d0d0

color8  #4e4e4e
color9  #ff8787
color10 #87af87
color11 #ffffaf
color12 #87afd7
color13 #af87af
color14 #87d7d7
color15 #ffffff

selection_background #22272e
selection_foreground #adbac7

# Kitty window border colors
active_border_color #2f2f2f
inactive_border_color #202020
bell_border_color       #F9E2AF

# Tabs
active_tab_background #4c4c4c
active_tab_foreground #1c1c1c
inactive_tab_background #1c1c1c
inactive_tab_background #1c1c1c
tab_bar_background #1c1c1c
