
# --- Hubbamax Color Scheme ---

background #1c1c1c
foreground #bcbcbc
cursor     #bcbcbc

color0  #1c1c1c
color8  #767676

color1  #af5f5f
color9  #d75f87

color2  #5faf5f
color10 #87d787

color3  #af875f
color11 #d7af87

color4  #5f87af
color12 #5fafd7

color5  #af87af
color13 #d787d7

color6  #5f8787
color14 #87afaf

color7  #9e9e9e
color15 #bcbcbc

selection_background #22272e
selection_foreground #adbac7

# Kitty window border colors
active_border_color #252525
inactive_border_color #191919
bell_border_color       #F9E2AF

# Tabs
active_tab_background #302B30
active_tab_foreground #6f5f6f
inactive_tab_background #1c1c1c
inactive_tab_background #1c1c1c
tab_bar_background #1c1c1c
