# vscode dark color scheme for Kitty
# By https://github/mofiqul

foreground            #e4e4e8
background            #060606
selection_foreground  #e4e4e8
selection_background  #404040
url_color             #e4e4e8

# Kitty window border colors
active_border_color   #121212
inactive_border_color #070707
bell_border_color       #F9E2AF

# Tabs
active_tab_background   #444444
active_tab_foreground   #060606
inactive_tab_background #060606
inactive_tab_background #060606
tab_bar_background      #060606

color0   #000000
color1   #e08585
color2   #6fbe80
color3   #c2916a
color4   #75a1c7
color5   #c4a8d6
color6   #75a1c7
color7   #c7c7c7
color8   #888888
color9   #e08585
color10  #6fbe80
color11  #d9a35a
color12  #8c9cb8
color13  #c4a8d6
color14  #75a1c7
color15  #ffffff
