
color0 #26233a
color1 #eb6f92
color2 #31748f
color3 #f6c177
color4 #3687a4
color5 #c4a7e7
color6 #ebbcba
color7 #e0def4
color8 #6e6a86
color9 #eb6f92
color10 #31748f
color11 #f6c177
color12 #9ccfd8
color13 #c4a7e7
color14 #ebbcba
color15 #e0def4

background #12171c
foreground #e0def4

cursor #fb4934
cursor_text_color #191724


selection_background #d8dee9
selection_foreground #2e3440

# Kitty window border colors
active_border_color #080a0d
inactive_border_color #13181e
bell_border_color       #F9E2AF

# Tabs
active_tab_background #344051
active_tab_foreground #12171c
inactive_tab_background #12171c
inactive_tab_background #12171c
tab_bar_background #12171c
