color0 #4d4d4d
color1 #7d5d5d
color2 #60b48a
color3 #f0dfaf
color4 #bbaf8d
color5 #dc8cc3
color6 #8cd0d3
color7 #dcdccc
color8 #709080
color9 #dca3a3
color10 #c3bf9f
color11 #e0cf9f
color12 #94bff3
color13 #ec93d3
color14 #93e0e3
color15 #ffffff

background #3f3f3f
foreground #dcdccc
cursor #A0E6A0

selection_tab_background #dfdad9
selection_tab_foreground #575279

# Kitty window border colors
active_border_color #121212
inactive_border_color #0c0c0c
bell_border_color       #F9E2AF

# Tabs
active_tab_background #20171F
active_tab_foreground #533c51
inactive_tab_background #050505
inactive_tab_background #050505
tab_bar_background #050505
