#!/bin/bash
# vim: foldmethod=indent foldlevel=0

set -e -u

PATH_CONKY="$HOME/.config/conky"

getxresources_col(){
  GETCOLOR=$(xrdb -query | grep "$1" | cut -d":" -f 2 | xargs | cut -d"#" -f2)
  sed -i -e "s/%%$2%%/$GETCOLOR/g" "$PATH_CONKY/$3"
}

rebuild_plugin(){
  [[ ! -f "$PATH_CONKY/rebuild-plugin/$1/main" ]] && notify-send "Conky plugin: path $1, not found. Abort" && exit

  cat "$PATH_CONKY/rebuild-plugin/$1/main" > "$PATH_CONKY/$1"
}

(
  # rebuild data
  rebuild_plugin "_p_clock_date"
  rebuild_plugin "_p_news_ytcombinator"

  # rebuild color untuk clock_date
  getxresources_col "color4" color_fg "_p_clock_date"
  getxresources_col "color2" color_fg_2 "_p_clock_date"
  getxresources_col "color8" color_fg_3 "_p_clock_date"
  getxresources_col "color15" default_color "_p_clock_date"
  getxresources_col "color6" default_shade_color "_p_clock_date"

  # rebuild color untuk ytcombinator
  getxresources_col "*.color4" color_uniq "_p_news_ytcombinator"
  getxresources_col "*.color4" color_uniq_1 "_p_news_ytcombinator"
  getxresources_col "*.color4" default_color "_p_news_ytcombinator"
  getxresources_col "*.color4" default_shade_color "_p_news_ytcombinator"
)
