#!/bin/bash

set -e -u
set -o nounset

# Date Created: 28 Feb 2019
# Last Modified: 28 Feb 2019 (18:11:56)
# Summary:
# Author: Gitmox
# License:

DATENOW=$(date +%-u)
MYMOXCONF="$HOME/Dropbox/mytodo"

function reset_calcurse() {
	# saving todo calcurse
	case $1 in
	senin | selasa | rabu) calcurse -x >"$MYMOXCONF/todos/todo.android" ;;
	kamis | jumat | sabtu) calcurse -x >"$MYMOXCONF/todos/todo.web" ;;
	minggu) calcurse -x >"$MYMOXCONF/todos/todo.localhost" ;;
	esac

	# make delay
	sleep 1

	# delete all todo before inject new todo
	echo -n "" >~/.calcurse/todo
}

function reload_calcurse() {
	SET_CALCURSE=$(jq -r ."$1".todo <"$MYMOXCONF/todo.json")

	# import calcurse todo
	calcurse -i "$MYMOXCONF/todos/$SET_CALCURSE" >/dev/null
}

function calltodo() {
	# cat .daycalltodo
	DAY=$(cat ~/.config/polybar/.daycalltodo)

	if [ "$1" == "$DAY" ]; then
		reset_calcurse "$1"
		reload_calcurse "$1"
	else
		echo -n "" >~/.calcurse/todo
		reload_calcurse "$1"

		# [Dont forget] dont remove this file  when you edit polybar path
		echo "$1" >~/.config/polybar/.daycalltodo
	fi
}

(
	CALCURSETEST=$(command -v calcurse)
	[[ -z $CALCURSETEST ]] && exit

	HARI=""
	case $DATENOW in
	1) HARI="senin" ;;
	2) HARI="selasa" ;;
	3) HARI="rabu" ;;
	4) HARI="kamis" ;;
	5) HARI="jumat" ;;
	6) HARI="sabtu" ;;
	7) HARI="minggu" ;;
	esac

	calltodo "$HARI"

	[ -f ~/.calcurse/todo ] && wc -l <~/.calcurse/todo
)
