#!/bin/bash

# Filename: diskusage
# Create three arrays, each indexed by numeric user ID
#    $sizes[] will accumulate the disk space consumed by each user

#    $uids[] will store the numeric user ID for each user
#    $users[] will store the user name for each user

# The caller will send us lines of the form
#    numeric-user-id filesize username

while read uid filesize user; do
  # Find the current amount of space used by this $uid
  size=${sizes[$uid]:-0}
  # Add the space consumed by this file and store it back
  # in $sized[$uid]
  let sizes[$uid]=$filesize+$size

  # Store the numeric user ID and user name too
  uids[$uid]=$uid users[$uid]=$user
done

# We’ve now accumulated all of the disk space usage
# for the caller, display the results
for uid in ${uids[*]}; do
  printf "%15d\t%s\n" "${sizes[$uid]}" "${users[$uid]}"
done
