#!/bin/bash

# Date Created: 10 Jul 2019
# Last Modified: 10 Jul 2019 (02:15:09)
# Summary:
# Author: Gitmox
# License:

# set -u -e

WALLI3IMG="$HOME/moxconf/media_and_tuts/walli3"

#####################################

# > TAK PERLU OTAK ATIK KODE DI BAWAH

#####################################

# [[ ! -d "$WALLI3IMG" ]] && exit 1

numberPath="$HOME/.cache/wallpaper"
numberFile="imgWall"

main() {
  local set_theme="general"
  if [[ -n "$1" ]]; then
    set_theme="$1"
  fi

  [[ ! -d $WALLI3IMG ]] && dunstify "Fehbg: path walli3=$WALLI3IMG not found!" && exit 1

  pathNumber="$numberPath/$numberFile"

  [[ ! -f "$pathNumber" ]] &&
    mkdir -p "$numberPath" &&
    touch "$pathNumber" &&
    echo "0" >"$pathNumber"

  # 1. Get all files inside path and then convert all them to array
  array=()
  while IFS= read -r -d $'\0'; do
    array+=("$REPLY")
  done < <(find "$WALLI3IMG" -type f -name "*" -print0)

  # 2. And now starting decrement sum of array
  totalNumImg=$((${#array[@]})) # get total length of array
  numImg="$(cat "$pathNumber")"

  if [ "$(cat "$pathNumber")" == 0 ]; then
    echo "$totalNumImg" >"$pathNumber"
  else
    ((totalNumImg = numImg - 1))
    echo "$totalNumImg" >"$pathNumber"
  fi

  nextImg="$((${#array[@]} - $(cat "$pathNumber")))"

  for i in "${!array[@]}"; do
    if [ "$i" == "$nextImg" ]; then
      if [[ $set_theme == "general" ]]; then
        feh --bg-scale "${array[$i]}"
      else
        if asdf which gowall >/dev/null; then
          gowall convert "${array[$i]}" -t "$set_theme" --output /tmp/newName.jpg >/dev/null
          feh --bg-scale /tmp/newName.jpg
        else
          feh --bg-scale "${array[$i]}"
        fi
      fi
      echo "${array[$i]}" >/tmp/bg-windows
    fi
  done
}

main "$@"
