#!/bin/bash

set -u -e

GET_FG=$(xrdb -query | grep -i foreground | cut -d':' -f2 | xargs)
GET_BG=$(xrdb -query | grep -i background | cut -d':' -f2 | xargs)

GET_BLACK=$(xrdb -query | grep -i .color0 | cut -d':' -f2 | head -1 | xargs)
GET_BLACK_ALT=$(xrdb -query | grep -i .color8 | cut -d':' -f2 | head -1 | xargs)

GET_RED=$(xrdb -query | grep -i .color1 | cut -d':' -f2 | head -1 | xargs)
GET_RED_ALT=$(xrdb -query | grep -i .color9 | cut -d':' -f2 | head -1 | xargs)

GET_GREEN=$(xrdb -query | grep -i .color2 | cut -d':' -f2 | head -1 | xargs)
GET_GREEN_ALT=$(xrdb -query | grep -i .color10 | cut -d':' -f2 | head -1 | xargs)

GET_YELLOW=$(xrdb -query | grep -i .color3 | cut -d':' -f2 | head -1 | xargs)
GET_YELLOW_ALT=$(xrdb -query | grep -i .color11 | cut -d':' -f2 | head -1 | xargs)

GET_BLUE=$(xrdb -query | grep -i .color4 | cut -d':' -f2 | head -1 | xargs)
GET_BLUE_ALT=$(xrdb -query | grep -i .color12 | cut -d':' -f2 | head -1 | xargs)

GET_MAGENTA=$(xrdb -query | grep -i .color5 | cut -d':' -f2 | head -1 | xargs)
GET_MAGENTA_ALT=$(xrdb -query | grep -i .color13 | cut -d':' -f2 | head -1 | xargs)

GET_CYAN=$(xrdb -query | grep -i .color6 | cut -d':' -f2 | head -1 | xargs)
GET_CYAN_ALT=$(xrdb -query | grep -i .color14 | cut -d':' -f2 | head -1 | xargs)

GET_WHITE=$(xrdb -query | grep -i .color7 | cut -d':' -f2 | head -1 | xargs)
GET_WHITE_ALT=$(xrdb -query | grep -i .color15 | cut -d':' -f2 | head -1 | xargs)

GET_COL_16=$(xrdb -query | grep -i .color16 | cut -d':' -f2 | head -1 | xargs)
GET_COL_17=$(xrdb -query | grep -i .color17 | cut -d':' -f2 | head -1 | xargs)

GET_COL_18=$(xrdb -query | grep -i .color18 | cut -d':' -f2 | head -1 | xargs)
GET_COL_19=$(xrdb -query | grep -i .color19 | cut -d':' -f2 | head -1 | xargs)

GET_COL_20=$(xrdb -query | grep -i .color20 | cut -d':' -f2 | head -1 | xargs)
GET_COL_21=$(xrdb -query | grep -i .color21 | cut -d':' -f2 | head -1 | xargs)
GET_COL_22=$(xrdb -query | grep -i .color22 | cut -d':' -f2 | head -1 | xargs)
GET_COL_23=$(xrdb -query | grep -i .color23 | cut -d':' -f2 | head -1 | xargs)
GET_COL_24=$(xrdb -query | grep -i .color24 | cut -d':' -f2 | head -1 | xargs)
GET_COL_25=$(xrdb -query | grep -i .color25 | cut -d':' -f2 | head -1 | xargs)

# GET_FONT="$(grep -i font <~/.cache/paintee | head -1 | awk -F= '{print $2}' | xargs)"
# GET_FONTSIZE="$(grep -i fontsize <~/.cache/paintee | head -1 | awk -F= '{print $2}' | xargs)"
# GET_BACKGROUND="$(grep -i background <~/.cache/paintee | head -1 | awk -F= '{print $2}' | xargs)"
# GET_BACKGROUND_VIM="$(grep -i background_vim <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_BACKGROUND_ACTIVE_WINDOW="$(grep -i background_active_window <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_BACKGROUND_NON_ACTIVE_WINDOW="$(grep -i background_non_active_window <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_BACKGROUND_NON_ACTIVE_STATUSLINE="$(grep -i background_non_active_statusline <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_FOREGROUND_WINSEPARATOR="$(grep -i foreground_winseparator <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_ACTIVE_FOREGROUND_WINSEPARATOR="$(grep -i active_foreground_winseparator <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_TMUX_PANE_ACTIVE_BG="$(grep -i tmux_pane_active_bg <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_TMUX_PANE_BG="$(grep -i tmux_pane_bg <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_TMUX_FG="$(grep -i tmux_fg <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_TMUX_BORDER_FG="$(grep -i tmux_border_fg <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_STATUSLINE="$(grep -i statusline <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_SEPARATOR_STATUSLINE="$(grep -i separator_statusline <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_STATUSLINE_FG="$(grep -i statusline_fg <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_WINSEPARATOR_FG="$(grep -i winseparator_fg <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_FZF_BG_SELECTION="$(grep -i fzf_bg_selection <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_FOREGROUND="$(grep -i foreground <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_RED="$(grep -i red <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_ALTRED="$(grep -i altred <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_WHITE="$(grep -i white <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_BLACK="$(grep -i black <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_GREEN="$(grep -i green <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_ALTGREEN="$(grep -i altgreen <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_CYAN="$(grep -i cyan <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_BLUE="$(grep -i blue <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_YELLOW="$(grep -i yellow <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_ALTYELLOW="$(grep -i altyellow <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"
# GET_MAGENTA="$(grep -i magenta <~/.cache/paintee | head -1 | awk -F= '{print $2}' | sed 's/\"//g')"

lighten_color() {
	hex_color="$1"
	factor="$2"

	# Validasi panjang HEX
	if [[ ${#hex_color} -ne 7 ]]; then
		echo "Error: HEX color must be in the format '#RRGGBB'."
		exit 1
	fi

	# Ekstraksi komponen warna
	r=$(printf "%d" 0x"${hex_color:1:2}")
	g=$(printf "%d" 0x"${hex_color:3:2}")
	b=$(printf "%d" 0x"${hex_color:5:2}")

	# Mencerahkan setiap komponen warna
	r=$(($r + $factor))
	g=$(($g + $factor))
	b=$(($b + $factor))

	# Batasi nilai maksimum ke 255
	r=$(($r > 255 ? 255 : $r))
	g=$(($g > 255 ? 255 : $g))
	b=$(($b > 255 ? 255 : $b))

	# Format kembali ke format HEX
	printf "#%02x%02x%02x\n" "$r" "$g" "$b"
}
darken_color() {
	hex_color="$1"
	factor="$2"

	# Validasi panjang HEX
	if [[ ${#hex_color} -ne 7 ]]; then
		echo "Error: HEX color must be in the format '#RRGGBB'."
		exit 1
	fi

	# Ekstraksi komponen warna
	r=$(printf "%d" 0x"${hex_color:1:2}")
	g=$(printf "%d" 0x"${hex_color:3:2}")
	b=$(printf "%d" 0x"${hex_color:5:2}")

	# Menggelapkan setiap komponen warna
	r=$(($r - $factor))
	g=$(($g - $factor))
	b=$(($b - $factor))

	# Batasi nilai minimum ke 0
	r=$(($r < 0 ? 0 : $r))
	g=$(($g < 0 ? 0 : $g))
	b=$(($b < 0 ? 0 : $b))

	# Format kembali ke format HEX
	printf "#%02x%02x%02x\n" "$r" "$g" "$b"
}

check_size_screen() {
	size=$(xrandr | grep "*" | xargs | cut -d" " -f1)

	if [[ $size == '1024x768' ]]; then
		FONTSIZE="12"
	else
		FONTSIZE="16"
	fi
}
