#!/bin/bash

set -e -u

#Date Created: 28 Nov 2018
#Last Modified: 28 Nov 2018 (13:48:04)
#Summary:
#Author: Gitmox
#License:

# TERM=$(which st)
# i3-msg "exec --no-startup-id $TERM -e mutt"

dunstify "mantap"
