#!/bin/bash

FZF_PATH="$HOME/moxconf/development/dotfiles/miscxrdb/.config/miscxrdb/fzf"
mastercolors="/tmp/masterColors"

[[ ! -f "$mastercolors" ]] && dunstify "file $mastercolors not exists, so abort" && exit 1

getcolors() {
	FOREGROUND="$(xrdb -query | grep 'foreground:' | awk '{print $NF}' | head -1)"
	BACKGROUND="$(xrdb -query | grep 'background:' | awk '{print $NF}' | head -1)"
	CURSOR="$(xrdb -query | grep 'cursorColor:' | awk '{print $NF}' | head -1)"
	BLACK="$(xrdb -query | grep 'color0:' | awk '{print $NF}' | head -1)"
	RED="$(xrdb -query | grep 'color1:' | awk '{print $NF}' | head -1)"
	GREEN="$(xrdb -query | grep 'color2:' | awk '{print $NF}' | head -1)"
	YELLOW="$(xrdb -query | grep 'color3:' | awk '{print $NF}' | head -1)"
	BLUE="$(xrdb -query | grep 'color4:' | awk '{print $NF}' | head -1)"
	MAGENTA="$(xrdb -query | grep 'color5:' | awk '{print $NF}' | head -1)"
	CYAN="$(xrdb -query | grep 'color6:' | awk '{print $NF}' | head -1)"
	WHITE="$(xrdb -query | grep 'color7:' | awk '{print $NF}' | head -1)"
	ALTBLACK="$(xrdb -query | grep 'color8:' | awk '{print $NF}' | head -1)"
	ALTRED="$(xrdb -query | grep 'color9:' | awk '{print $NF}' | head -1)"
	ALTGREEN="$(xrdb -query | grep 'color10:' | awk '{print $NF}' | head -1)"
	ALTYELLOW="$(xrdb -query | grep 'color11:' | awk '{print $NF}' | head -1)"
	ALTBLUE="$(xrdb -query | grep 'color12:' | awk '{print $NF}' | head -1)"
	ALTMAGENTA="$(xrdb -query | grep 'color13:' | awk '{print $NF}' | head -1)"
	ALTCYAN="$(xrdb -query | grep 'color14:' | awk '{print $NF}' | head -1)"
	ALTWHITE="$(xrdb -query | grep 'color15:' | awk '{print $NF}' | head -1)"
	FONTSIZE="18"
	FONT="mononoki Nerd Font"

	#BACKGROUND_ACTIVE_WINDOW: get bg dari 'hi Normal'
	#BACKGROUND_NON_ACTIVE_WINDOW: get bg dari colorcolumn

	#BACKGROUND_ACTIVE_STATUSLINE: get bg dari `hi StatusLine`
	#BACKGROUND_NON_ACTIVE_STATUSLINE: sama kan dengan BACKGROUND_NON_ACTIVE_WINDOW,
	#                                  atau -1 hex dari bg 'hi Normal'

	#FOREGROUND_WINSEPARATOR: get bg dari `hi WinSepator`
	#FZF_BG_SELECTION: get bg dari `hi PmenuSel`
	# Note: color FZF_BG_SELECTION juga digunakan untuk bg selection di rofi

	normal_fg=$(grep "normal_fg" <$mastercolors | awk '{print $NF}' | head -1)
	normal_bg=$(grep "normal_bg" <$mastercolors | awk '{print $NF}' | head -1)
	fzf_selection_fg=$(grep "fzf_selection_fg" <$mastercolors | awk '{print $NF}' | head -1)
	fzf_selection_bg=$(grep "fzf_selection_bg" <$mastercolors | awk '{print $NF}' | head -1)
	fzf_selection_match_fg=$(grep "fzf_selection_match_fg" <$mastercolors | awk '{print $NF}' | head -1)

	# non_fzf_fg=$(grep "non_fzf_fg" <$mastercolors | awk '{print $NF}' | head -1)
	# non_fzf_bg=$(grep "non_fzf_bg" <$mastercolors | awk '{print $NF}' | head -1)
	non_fzf_match_fg=$(grep "non_fzf_match_fg" <$mastercolors | awk '{print $NF}' | head -1)
	fzf_border_fg=$(grep "fzf_border_fg" <$mastercolors | awk '{print $NF}' | head -1)

	tmux_pane_active_bg=$(grep "tmux_pane_active_bg" <$mastercolors | awk '{print $NF}' | head -1)
	tmux_pane_bg=$(grep "tmux_pane_bg" <$mastercolors | awk '{print $NF}' | head -1)
	tmux_fg=$(grep "tmux_fg" <$mastercolors | awk '{print $NF}' | head -1)
	tmux_border_fg=$(grep "tmux_border_fg" <$mastercolors | awk '{print $NF}' | head -1)

	BACKGROUND_ACTIVE_WINDOW=$normal_bg
	BACKGROUND_NON_ACTIVE_WINDOW=$normal_bg

	BACKGROUND_ACTIVE_STATUSLINE=$normal_bg
	BACKGROUND_NON_ACTIVE_STATUSLINE=$normal_bg

	FOREGROUND_WINSEPARATOR=#003746

	FZF_BG_SELECTION=$fzf_selection_bg
	FZF_FG_SELECTION=$fzf_selection_fg
	FZF_FG_FUZZY_SELECTION=$fzf_selection_match_fg
	# Non selection fzf
	# FZF_BG=$non_fzf_bg
	FZF_FG=$normal_fg
	FZF_FG_FUZZY=$non_fzf_match_fg

	FZF_FG_BORDER=$fzf_border_fg

	# TMUX
	TMUX_PANE_ACTIVE_BG=$tmux_pane_active_bg
	TMUX_PANE_BG=$tmux_pane_bg

	TMUX_FG=$tmux_fg
	TMUX_BORDER_FG=$tmux_border_fg

}

_check_size_screen() {
	size=$(xrandr | grep "*" | xargs | cut -d" " -f1)

	if [[ $size == '1024x768' ]]; then
		FONTSIZE="12"
	else
		FONTSIZE="16"
	fi
}

cachecolors() {
	read -r -d '' cache <<-EOF
		  FOREGROUND="${FOREGROUND}"
		  BACKGROUND="${BACKGROUND}"

		  BACKGROUND_ACTIVE_WINDOW="${BACKGROUND_ACTIVE_WINDOW}"
		  BACKGROUND_NON_ACTIVE_WINDOW="${BACKGROUND_NON_ACTIVE_WINDOW}"

		  BACKGROUND_ACTIVE_STATUSLINE="${BACKGROUND_ACTIVE_STATUSLINE}"
		  BACKGROUND_NON_ACTIVE_STATUSLINE="${BACKGROUND_NON_ACTIVE_STATUSLINE}"

		  FOREGROUND_WINSEPARATOR="${FOREGROUND_WINSEPARATOR}"

		  FZF_BG_SELECTION="${FZF_BG_SELECTION}"

		  TMUX_FG="${TMUX_FG}"
		  TMUX_BORDER_FG="${TMUX_BORDER_FG}"

		  TMUX_PANE_ACTIVE_BG="${TMUX_PANE_ACTIVE_BG}"
		  TMUX_PANE_BG="${TMUX_PANE_BG}"

		  CURSOR="${CURSOR}"
		  BLACK="${BLACK}"
		  RED="${RED}"
		  GREEN="${GREEN}"
		  YELLOW="${YELLOW}"
		  BLUE="${BLUE}"
		  MAGENTA="${MAGENTA}"
		  CYAN="${CYAN}"
		  WHITE="${WHITE}"
		  ALTBLACK="${BLACK}"
		  ALTRED="${RED}"
		  ALTGREEN="${GREEN}"
		  ALTYELLOW="${YELLOW}"
		  ALTBLUE="${BLUE}"
		  ALTMAGENTA="${MAGENTA}"
		  ALTCYAN="${CYAN}"
		  ALTWHITE="${WHITE}"
		  FONT="${FONT}"
		  FONTSIZE="${FONTSIZE}"
	EOF
}
cachecolorfzf() {
	read -r -d "" cachefzf <<-EOF

		  function _gen_fzf_default_opts() {

				    # --files: List files that would be searched but do not search
				    # --no-ignore: Do not respect .gitignore, etc...
				    # --hidden: Search hidden files and folders
				    export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden --smart-case'

				    # export FZF_DEFAULT_COMMAND='rg --no-heading --hidden --follow --no-ignore-vcs --smart-case '
		        export FZF_CTRL_T_COMMAND='fd --hidden --follow --exclude .git'

				    export FZF_DEFAULT_OPTS='
		        --bind ctrl-a:toggle-all,ctrl-l:clear-query,ctrl-d:preview-down,ctrl-u:preview-up,ctrl-n:down,ctrl-p:up,ctrl-g:top,F3:toggle-preview,ctrl-f:half-page-down,ctrl-b:half-page-up
				    --color=bg+:$FZF_BG_SELECTION,fg+:$FZF_FG_SELECTION,hl+:$FZF_FG_FUZZY_SELECTION,gutter:$TMUX_PANE_BG,pointer:$GREEN
				    --color=bg:$BACKGROUND_NON_ACTIVE_WINDOW,fg:$FZF_FG,hl:$FZF_FG_FUZZY,border:$FZF_FG_BORDER --height=65%
		        --preview "bat --style=plain --color=always {}" --preview-window right:50%:hidden:wrap --border --reverse
				    --cycle --prompt="> "'
				}

				_gen_fzf_default_opts
	EOF
}

sendescape() {
	for term in /dev/pts/[0-9]*; do
		printf "%b" "\\033]10;$FOREGROUND\\007" >"$term" &
		printf "%b" "\\033]11;$BACKGROUND\\007" >"$term" &
		printf "%b" "\\033]708;$BACKGROUND\\007" >"$term" &
		printf "%b" "\\033]12;$CURSOR\\007" >"$term" &
		printf "%b" "\\033]4;0;$BLACK\\007" >"$term" &
		printf "%b" "\\033]4;1;$RED\\007" >"$term" &
		printf "%b" "\\033]4;2;$GREEN\\007" >"$term" &
		printf "%b" "\\033]4;3;$YELLOW\\007" >"$term" &
		printf "%b" "\\033]4;4;$BLUE\\007" >"$term" &
		printf "%b" "\\033]4;5;$MAGENTA\\007" >"$term" &
		printf "%b" "\\033]4;6;$CYAN\\007" >"$term" &
		printf "%b" "\\033]4;7;$WHITE\\007" >"$term" &
		printf "%b" "\\033]4;8;$ALTBLACK\\007" >"$term" &
		printf "%b" "\\033]4;9;$ALTRED\\007" >"$term" &
		printf "%b" "\\033]4;10;$ALTGREEN\\007" >"$term" &
		printf "%b" "\\033]4;11;$ALTYELLOW\\007" >"$term" &
		printf "%b" "\\033]4;12;$ALTBLUE\\007" >"$term" &
		printf "%b" "\\033]4;13;$ALTMAGENTA\\007" >"$term" &
		printf "%b" "\\033]4;14;$ALTCYAN\\007" >"$term" &
		printf "%b" "\\033]4;15;$ALTWHITE\\007" >"$term" &
	done
}

main() {
	if [ -e ~/.cache/paintee ]; then
		rm ~/.cache/paintee
	fi

	getcolors
	_check_size_screen
	cachecolors
	echo "$cache" >~/.cache/paintee

	cachecolorfzf
	echo "$cachefzf" >"$FZF_PATH/fzf.config"
}

main
