#!/bin/bash

set -e -u

start=$(date +%s)
if [[ $1 == ?([+-])+([0-9]) ]]; then
	((start += $1))
elif [[ $1 ]]; then
	echo "invalid argument '$1': ignoring it"
fi

while true; do
	now=$(date +%s)
	days=$(((now - start) / 86400))
	seconds=$(((now - start) % 86400))
	printf '\r%d day(s) and %s ' "$days" "$(date --utc --date @"$seconds" +%T)"
	sleep 0.1
done
