#!/bin/bash

BOOMARKS_DIR="$HOME/Dropbox/exbin/bookmarks"
dir="$HOME/.config/rofi/menu"
theme="styles/big_screen"
rofi_command="rofi -theme $dir/$theme"

(
	[[ ! -d $BOOMARKS_DIR ]] && dunstify "Bookmarks" "Path: $BOOMARKS_DIR not found" && exit 0

	SELECT=$(cat "$BOOMARKS_DIR/urlist" | awk '/^[a-z]/' | awk -F"{" '{printf "%s %-31s %s\n", $1,$2,$3}' |
		$rofi_command -dmenu -p " ")

	# # grep list url, but ignore the '#' symbol
	# # SELECT=$(grep "^[^#;]" "$BOOMARKS_DIR"/urlist | sort | rofi -i -l 10 -dmenu -p "[firefox]browser")
	# load_vars_rofi "bookmarks"
	# SELECT=$(grep "^[^#;]" $BOOMARKS_DIR/urlist \
	# 	| awk -F"{" '{printf "%-20s %s\n",$1,$2}' | rofi -width "$WIDTH" \
	# 	-columns "$COLUMNS" -lines "$LINES" \
	# 	-bw 1 -location "$LOCATION" -xoffset "$XOFFSET" -yoffset "$YOFFSET" \
	# 	-dmenu -format "$FORMAT" -p "$PROMPT")

	# # check jika $SELECT, sudah di set
	[[ -z $SELECT ]] && exit

	# # grab url, with cut command select area kedua
	GRAB_URL=$(echo "$SELECT" | xargs | rev | cut -d" " -f1 | rev)

	firefox "$GRAB_URL"

)
