#!/bin/bash

set -e

MENULIST_PATH="$HOME/Dropbox/neorg"
# dir="$HOME/.config/rofi/menu"
# theme="styles/big_center"
# rofi_command="rofi -theme $dir/$theme"
[[ ! -d $MENULIST_PATH ]] && dunstify "GLinux:" "Path $MENULIST_PATH not found"

# SELECT="$(rg . "$MENULIST_PATH" --column --no-heading --hidden --follow --smart-case -g "!*.md" | $rofi_command -dmenu -i -p "  " | cut -d':' -f1)"

# rg . ~/Dropbox/neorg --column --no-heading --hidden --follow --smart-case -g "!*.md" | awk -F: '
#  function basename(file, a, n) {
#     n = split(file, a, "/")
#     return a[n]
#   }
# {printf "%s %-10s\n", basename($1), $4 }' | rofi -theme ~/.config/rofi/menu/styles/big_center.rasi -dmenu -i -p "  " | awk -F: f1

# call_bspc() {
# 	bspc rule -a \* -o state=floating center=true rectangle=800x500+0+0 &&
# 		kitty -e nvim "$1"
# }

# (
# 	[[ -z $SELECT ]] && exit
# 	call_bspc "$SELECT"
# )

# -----------------------------------------------
# new
# -----------------------------------------------

call_bspc() {
	bspc rule -a \* -o state=floating center=true rectangle=1200x600+0+0 &&
		kitty -e bash -c "rg . $MENULIST_PATH --color=always --colors=path:fg:magenta --colors=column:fg:red --colors=match:fg:yellow --colors=match:style:bold --line-number --no-heading --smart-case |
	fzf -d ":" -n 3.. --ansi --preview 'bat --highlight-line {2} --color=always {1} --line-range={2}:+30'  --bind ctrl-a:toggle-all,ctrl-l:clear-query,ctrl-d:preview-down,ctrl-u:preview-up,ctrl-n:down,ctrl-p:up,ctrl-g:top,F4:toggle-preview | 
  cut -z -d : -f 1 | xargs -0 -r nvim"

}

(
	call_bspc
)
