#!/bin/bash

set -e -u

SNIPPETS_MENU="aliases\nnewsboat\nsurfingkeys\nsxhkdrc\ntmux\nvimium\nzathura"

dir="$HOME/.config/rofi/menu"
theme="styles/snippets"
rofi_command="rofi -theme $dir/$theme"

SELECT="$(echo -e "$SNIPPETS_MENU" | $rofi_command -p "  " -dmenu -i)"

(
  [[ -z $SELECT ]] && exit

  "$HOME/.config/miscxrdb/exbin/showlinuxhelp" "$SELECT"

  exit
)
