#!/bin/bash

dir="$HOME/.config/rofi/menu"
theme="styles/menuleft"
rofi_command="rofi -theme $dir/$theme"
MENULIST_PATH="Calendar\nFile manager\nKeyboard\nRecording Fullscreen\nRecording Rectangle\nRecording Gif\nStop Recording\nScreenshot\nDrawing"

# For record video
PATH_VIDEOS="$HOME/Downloads/screenshot/videos"
FILE_RECORDING_BAK="$PATH_VIDEOS/ffmpeg-bak-$(date +%d_%m_%Y_%s).mp4"
FILE_NAME_RECORD="ffmpeg-$(date +%d_%m_%Y_%s).mp4"
FILE_RECORDING="$PATH_VIDEOS/$FILE_NAME_RECORD"
# COL_MSG_SUCCSS="$(xrdb -query | grep "color3" | head -n 1 | cut -d":" -f2 | xargs)"

(
	SELECT="$(echo -e "$MENULIST_PATH" | $rofi_command -p "  " -dmenu -i)"

	[[ -z $SELECT ]] && exit

	run_screenkey() {
		SCREENKEY=$(command -v screenkey)
		pidof "$SCREENKEY" && killall "$SCREENKEY"
		$SCREENKEY
	}

	run_ffmpeg_record_fullscreen() {

		GEOMETRY=$(xwininfo -root | awk '/geometry/ {gsub("+.*",""); print $2}')
		FPS="30"

		FILE_ICONS="$HOME/Dropbox/data.programming.forprivate/icons/rec-button.png"
		if [ -f "$FILE_ICONS" ]; then
			dunstify "Record" "starting.." -i "$FILE_ICONS"
		else
			dunstify "Record" "starting.."
		fi

		ffmpeg -f x11grab -s "$GEOMETRY" -r "$FPS" -i :0.0 -f alsa -ac 2 \
			-i default -vcodec libx264 -s "$GEOMETRY" \
			-acodec libmp3lame -ab 128k -ar 44100 \
			-threads 0 -f flv "$FILE_RECORDING_BAK"

		# For telegram
		ffmpeg -i "$FILE_RECORDING_BAK" -crf 23 -preset veryfast -vcodec libx264 -acodec aac -pix_fmt yuv420p "$FILE_RECORDING"

		if [ -f "$FILE_RECORDING_BAK" ]; then
			rm -rf "$FILE_RECORDING_BAK"
			# dunstify "Saving to:" "<b><span font='JetBrainsMono Nerd Font 12' foreground='$COL_MSG_SUCCSS'>$FILE_RECORDING</span></b>"
			dunstify "Saving record:" "$FILE_NAME_RECORD"
		fi

	}

	run_ffmpeg_record_with_rectangle() {
		GEOMETRY=$(xwininfo -root | awk '/geometry/ {gsub("+.*",""); print $2}')
		SLOP_INFO=$(slop -f "%wx%h+%x,%y")

		FILE_ICONS="$HOME/Dropbox/data.programming.forprivate/icons/rec-button.png"
		if [ -f "$FILE_ICONS" ]; then
			dunstify "Record" "starting.." -i "$FILE_ICONS"
		else
			dunstify "Record" "starting.."
		fi

		GEOMETRY=$(echo "$SLOP_INFO" | awk -F "+" '{print $1}')
		OFFSET=$(echo "$SLOP_INFO" | awk -F "+" '{print "+"$2}')

		ffmpeg -f x11grab -s "$GEOMETRY" -r 30 -i :0.0"$OFFSET" -f alsa -ac 2 \
			-i default -vcodec libx264 -s "$GEOMETRY" \
			-acodec libmp3lame -ab 128k -ar 44100 \
			-threads 0 -f flv "$FILE_RECORDING_BAK"

		# For telegram
		ffmpeg -i "$FILE_RECORDING_BAK" -crf 23 -preset veryfast -vcodec libx264 -acodec aac \
			-vf 'scale=-2:min(1080\,bitand(ih\,-2))' \
			-pix_fmt yuv420p "$FILE_RECORDING"

		if [ -f "$FILE_RECORDING_BAK" ]; then
			rm -rf "$FILE_RECORDING_BAK"
			dunstify "Saving record:" "$FILE_NAME_RECORD"
		fi

	}

	run_ffmpeg_stop() {
		pkill ffmpeg
		dunstify "Record" "quit.."
	}

	run_simplegif() {
		if [ -n "$(command -v giph)" ]; then
			giph -s -l -c 1,1,1,0.3 -b 5 -p -5 -d 3 -t 10 "$HOME/Downloads/screenshot/$(date +%s).gif"
		else
			# check install here: https://github.com/phisch/giph
			dunstify ":you need install giph"
		fi

	}

	run_filemanager() {
		FILEMANAGER=$(command -v nautilus)
		pidof "$FILEMANAGER" && killall "$FILEMANAGER"

		nautilus
	}

	case "$SELECT" in
	"Calendar") gnome-calendar ;;
	"Keyboard") run_screenkey ;;
	"Drawing") gromit-mpx ;; # install: sudo apt install gromit-mpx
	"Screenshot") "$HOME/.config/rofi/scripts/takescreenshot" ;;
	"Recording Fullscreen") run_ffmpeg_record_fullscreen ;;
	"Recording Rectangle") run_ffmpeg_record_with_rectangle ;;
	"Recording Gif") run_simplegif ;;
	"Stop Recording") run_ffmpeg_stop ;;
	"File manager") run_filemanager ;;

	esac

)
