#!/bin/bash

MPV_LISTS="open\nopen with proxychains"
dir="$HOME/.config/rofi/menu"
theme="styles/snippets"
rofi_command="rofi -theme $dir/$theme"

is_file_exists() {
  if [[ ! -f "$1" ]]; then
    dunstify -u critical "Showlinuxhelp" "File path '$1' does not exist or has been deleted."
    exit
  fi
}

is_dir_exists() {
  if [[ ! -d "$1" ]]; then
    dunstify -u critical "Showlinuxhelp" "Directory path '$1' does not exist or has been deleted."
    exit
  fi
}

open_float() {
  # Open a command in float mode
  if [ "$1" == "calcurse" ]; then
    bspc rule -a \* -o state=floating center=true rectangle=800x500+0+0 && kitty -e bash -c "export VISUAL=nvim; calcurse"
  elif [ "$1" == 'ncmpcpp-ueberzug' ]; then
    bspc rule -a \* -o state=floating center=true rectangle=800x500+0+0 && kitty -e "$1"
  elif [ "$1" == 'ncmpcpp' ] || [ "$1" == 'rmpc' ]; then
    bspc rule -a \* -o state=floating center=true rectangle=1500x800+0+0 && $TERMINAL -e "$1"
  else
    bspc rule -a \* -o state=floating center=true rectangle=800x500+0+0 && kitty -e "$1"
  fi
}

open_note() {
  DIR_NOTES="$HOME/Dropbox"

  # elif [ "$1" == 'addnote' ]; then
  # bspc rule -a \* -o state=floating center=true rectangle=1200x800+0+0 && kitty -e \
  # zsh -i -c "source ~/.fzf.zsh; nvim -c \"lua require('orgmode').action('capture.prompt', { opts = { buffer = false, desc = 'org capture' } })\""

  # bspc rule -a \* -o state=floating center=true rectangle=1200x800+0+0 && $TERMINAL -e \ %%
  #   zsh -i -c "source ~/.fzf.zsh; nvim ~/Dropbox/neorg/orgmode/gtd/inbox.org" %%

  is_dir_exists "$DIR_NOTES"
  bspc rule -a \* -o state=floating center=true rectangle=1600x900+0+0 && $TERMINAL -e \
    zsh -i -c "cd $DIR_NOTES; nvim"
}

open_mpv() {
  SELECT="$(echo -e "$MPV_LISTS" | sort | $rofi_command -p " 🗂  MPV" -dmenu -i)"

  [[ -z $SELECT ]] && exit

  MSG_DUNST="MPV"
  MSG_PROXYCHAINS=""
  MSG_ICON="->"
  CLIPBOARD_SEL="$(xclip -o -sel clip)"

  [[ -z "$CLIPBOARD_SEL" ]] && exit

  if [[ $SELECT == "open with proxychains" ]]; then
    MSG_PROXYCHAINS="with proxychains"
    tsp proxychains -q mpv -ontop -no-border -force-window --autofit=853x500 --geometry=-15-60 --ytdl-raw-options="yes-playlist=,format=best" "$CLIPBOARD_SEL"
  else
    tsp mpv -ontop -no-border -force-window --autofit=800x500 --geometry=-15-60 "$CLIPBOARD_SEL"
  fi

  dunstify "Bspwmfloat" "$MSG_DUNST $MSG_PROXYCHAINS $MSG_ICON $CLIPBOARD_SEL"
}

remember_me_snippet() {
  SPAWN_TERMINAL=$TERMINAL
  [[ $TERMINAL == "wezterm" ]] && SPAWN_TERMINAL="st"

  SNIPPET_PATH="$HOME/.config/miscxrdb/bin/snippet"
  is_file_exists "$SNIPPET_PATH"
  bspc rule -a \* -o state=floating center=true rectangle=1500x800+0+0 && $SPAWN_TERMINAL -e zsh -e "$SNIPPET_PATH"

  # test
  # SNIPPET_PATH="$HOME/.config/miscxrdb/bin/snippet_test"
  # is_path_exits "$SNIPPET_PATH"
  # bspc rule -a \* -o state=floating center=true rectangle=1500x800+0+0 && st -e zsh -c "$SNIPPET_PATH"
}

"$@"
