#!/bin/bash

# : "${GREEN:=0x0000ff}"
# : "${BLUE:=0x00ff00}"
# : "${inactive:=0xff0000}"#
#
# while bspc subscribe -c 1 node_focus node_state >/dev/null; do
#
# 	bspc config focused_border_color "$(bspc config focused_border_color)"
#
# 	bspc query -N -n '.marked.!focused.window' | while read -r wid; do
# 		chwb -c "$GREEN" "$wid"
# 	done
# 	bspc query -N -n '.marked.active.!focused.window' | while read -r wid; do
# 		chwb -c "$BLUE" "$wid"
# 	done
# 	bspc query -N -n "focused.marked" | while read -r wid; do
# 		chwb -c "$inactive" "$wid"
# 	done
# done

# on=4 off=0
# bspc query -N -n .floating.window | xargs -I {node} bspc config -n {node} border_width "$on"
# bspc query -N -n .!floating.window | xargs -I {node} bspc config -n {node} border_width "$off"
# while read -r _ _ _ node state status; do
# 	[[ "$state" == "floating" ]] && bspc config -n "$node" border_width "${!status}"
# done < <(bspc subscribe node_state)
