#!/bin/bash

make_call() {
  if [ ! -f "$1" ]; then
    touch "$1"
    bspc node "$2" -d "^1"
    # bspc node -f east
  else
    bspc node "$2" -d "^$3"
    rm "$1"
  fi

}

toggle_call_win() {
  MARK_FILE="/tmp/.keep_$1"
  POSITION_WIN=$2

  for VAR in $(bspc query -N); do
    # output dari $VAR adalah 0x041xx (number window id)
    # output dari xdotool getwindowname "$VAR" (berupa string)

    # check apakah getwindowname name dari $VAR contains string mozilla
    if [ "$1" == "firefox" ]; then
      if [[ $(xdotool getwindowname "$VAR") == *"Mozilla"* ]] || [[ $(xdotool getwindowname "$VAR") == *"Zen Browser"* ]]; then
        make_call "$MARK_FILE" "$VAR" "$POSITION_WIN"
        break
      fi
    fi

    if [ "$1" == "zathura" ]; then
      if [[ $(xdotool getwindowname "$VAR") == *".pdf"* ]]; then
        make_call "$MARK_FILE" "$VAR" "$POSITION_WIN"
        break
      fi
    fi
  done
}

set_win_state() {
  # Original: bspc node -g {locked,sticky}
  MSG_BSPC_TITLE="BSPC-WINCALL"
  MSG_STATE="State ="

  if [[ $1 == "locked" ]]; then
    STATUS="locked"
    if [[ ! -f /tmp/bspwm-locked-status ]]; then
      STATUS="Unlocked"
      touch /tmp/bspwm-locked-status
    else
      rm /tmp/bspwm-locked-status
    fi
    bspc node -g locked
    dunstify "$MSG_BSPC_TITLE" "$MSG_STATE $STATUS"
  fi

  if [[ $1 == "sticky" ]]; then
    STATUS="unsticky"
    if [[ ! -f /tmp/bspwm-sticky-status ]]; then
      STATUS="sticky"
      touch /tmp/bspwm-sticky-status
    else
      rm /tmp/bspwm-sticky-status
    fi
    bspc node -g sticky
    dunstify "$MSG_BSPC_TITLE" "$MSG_STATE $STATUS"
  fi

}

"$@"
