#!/bin/bash

NEWLAYER=normal
if bspc query -N -n focused.normal > /dev/null; then
  NEWLAYER=below
elif bspc query -N -n focused.below > /dev/null; then
  NEWLAYER=above
fi

dunstify "$LAYER → $NEWLAYER"

# Apply new ratio
bspc node $NODE -l $NEWLAYER
