#!/bin/bash

MENU="dmenu"
FILE="$HOME/Dropbox/data.programming.forprivate/urlquery"
FILE_BOOKMARKED="$HOME/Dropbox/data.programming.forprivate/urlbookmarked"

ROFI_DIR="$HOME/.config/rofi/menu"
ROFI_THEME="styles/snippets"
ROFI_COMMAND="rofi -theme $ROFI_DIR/$ROFI_THEME"

MENU_FONT="SF Mono 24"

test_file_dir() {
	if [ ! -f "$1" ]; then
		if command -v dunstify >/dev/null; then
			dunstify "$2"
		else
			echo "$2"
		fi
		touch "$1"
		exit
	fi
}

NOTIFY_ME="[ERROR]: file $FILE not found"
NOTIFY_ME_BOOKMARKED="[ERROR]: file $FILE_BOOKMARKED not found"

test_file_dir "$FILE" "$NOTIFY_ME"
test_file_dir "$FILE_BOOKMARKED" "$NOTIFY_ME_BOOKMARKED"

FILEOPT=$(cat "$FILE")

OPTIONS="
[
${FILEOPT}
[ \"Add:New:Query\", \"\" ],
[ \"Add:New:Bookmark\", \"\" ],
[ \"Open:Bookmarked\", \"\" ],
[ \"Delete:Query\",  \"\" ],
[ \"Delete:Bookmarked\",  \"\" ],
[ \"Edit:Bookmarked\",  \"\" ],
[ \"Open:Pass\",  \"\" ]
]
"

OBJ_LENGTH=$(echo "$OPTIONS" | jq length)
OBJ_MENU=$(echo "$OPTIONS" | jq -r ".[][0]" | $MENU -i -p " WebSearch:" -fn "$MENU_FONT")
OBJ_SELECTED=$(echo "$OBJ_MENU" | cut -d' ' -f1)
OBJ_KEYWORDS=$(echo "$OBJ_MENU" | cut -d' ' -f2- | tr " " "+")

add_query() {
	PREFIXMENU=$(echo "" | dmenu -p "Add prefix menu:" -fn "$MENU_FONT" <&-)
	if [ -n "$PREFIXMENU" ]; then
		URLQUERY=$(echo "" | dmenu -p "Add url query:" -fn "$MENU_FONT" <&-)
		echo "[ \"$PREFIXMENU\", \"$URLQUERY\" ]," >>"$FILE"
	fi
	exit
}

delete_query() {
	if [ "$1" == "DMENU" ]; then
		OBJ_MENU=$(echo "$OPTIONS" | jq -r ".[][0]" | head -n -2 | $MENU -i -p "Delete Menu:" -fn "$MENU_FONT")
	else
		OBJ_MENU=$(awk -F"," '{printf "%-10s%s%-10s%s%-10s\n", $1,OFS,$2,OFS,$3}' OFS="," "$FILE_BOOKMARKED" |
			sort | awk -F"," '{print $1,$3}' |
			column -t -s"+" | $ROFI_COMMAND -dmenu -i -p "  " | awk -F"[[:space:]][[:space:]][[:space:]]+" '{print $1}')
	fi

	OBJ_SELECTED=$OBJ_MENU

	if [ -n "$OBJ_SELECTED" ]; then
		CONFIRM_DELETE=$(echo -e "no\nyes" | dmenu -p "Do you want to delete this url?" -fn "$MENU_FONT")
		if [ "$CONFIRM_DELETE" = "yes" ]; then
			sed -i "/$OBJ_SELECTED/d" "$2"
		fi
	fi
	exit
}

add_bookmark() {
	GET_CLIPCOPY=$(xclip -selection c -o)
	if [ -z "$GET_CLIPCOPY" ]; then
		dunstify "url: empty, abort"
		exit
	fi

	SET_TAGS=$(echo -e "hacky\ndotfiles\ntodo\ntutorial\ntorrent\nforum\ngithub\nfun\ntips\ndevs\nmoneygame\nwallpaper" | dmenu -p "Tags:" -fn "$MENU_FONT")
	if [ -z "$SET_TAGS" ]; then
		dunstify "[!] there is no tag insert, so abort it"
		exit
	fi

	DESCRIPTION=$(echo "" | dmenu -fn "$MENU_FONT" -p "Add description:" <&-)

	if [ -n "$DESCRIPTION" ]; then
		# PREFIX_DAT=$(echo "$GET_CLIPCOPY" | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')
		dunstify "url: $GET_CLIPCOPY adding to our bookmarked"
		# echo "$DESCRIPTION,$SET_TAGS,$PREFIX_DAT,+$GET_CLIPCOPY" >>"$FILE_BOOKMARKED"
		echo "$DESCRIPTION,$SET_TAGS,+$GET_CLIPCOPY" >>"$FILE_BOOKMARKED"
	fi
	exit
}

open_bookmarked() {
	# OPTIONS=$(cat "$FILE_BOOKMARKED" | sort | $ROFI_COMMAND -dmenu -i -p "  " | cut -d"," -f2)
	OPTIONS=$(
		awk -F"," '{printf "%-10s%s%-10s%s%-10s\n", $1,OFS,$2,OFS,$3}' OFS="," "$FILE_BOOKMARKED" |
			sort | column -t -s"," | $ROFI_COMMAND -dmenu -i -p "  " |
			tr -s " " | awk -F"+" '{print $2}'
	)
	xdg-open "$OPTIONS" 2>/dev/null
	exit
}

edit_bookmarked() {
	# kalau bukan bspwm, ini bakal error
	bspc rule -a \* -o state=floating center=true rectangle=800x500+0+0 &&
		kitty -e bash -c "/usr/local/bin/nvim ~/Dropbox/data.programming.forprivate/urlbookmarked"

	exit
}

open_pass() {
	# timeout=30

	select_password() {
		find "$dir" -not -path '*/.git/*' -type f |
			grep '\.gpg$' |
			sed "s:$dir\(.*\)\.gpg$:\1:" |
			$ROFI_COMMAND -dmenu -matchin fuzzy -i -sort -sorting-method fzf -p 'password' -filter "$1"
	}

	select_command() {
		copy_pasword_or_username() {
			selection="username"
			if [[ $1 == "password" ]]; then
				selection="$1"
			elif [[ $1 == "url" ]]; then
				selection=$1
			fi

			mypass=$(cat /tmp/mypass)
			if [[ $selection == "username" ]]; then
				pass "$mypass" | grep '^username: ' | cut -b 11- | xclip -sel clip
			elif [[ $selection == "password" ]]; then
				pass "$mypass" | grep '^password: ' | cut -b 11- | xclip -sel clip
			else
				# pass "$mypass" | grep '^url: ' | cut -b 5- | xargs xdg-open {}
				url=$(pass "$mypass" | grep '^url: ' | cut -b 6-)
				firefox "$url"
			fi
		}

		bspwm_open_float() {
			mypass=$(cat /tmp/mypass)
			if [[ $1 == "create_pass" ]]; then

				sel=$(echo "$mypass" | sed -r "s/(.+)\/.+/\1/")
				get_the_name=$(echo "" | $ROFI_COMMAND -dmenu -p "$sel")
				if [[ "$sel" == *\/* ]] || [[ "$sel" == *\\* ]]; then
					new_acc_pass="$sel/$get_the_name"
				else
					new_acc_pass="$get_the_name"
				fi

				# `new_acc_pass` harus contains some string
				# untuk memastikan `create pass` bisa berjalan lancar
				if [[ -n $new_acc_pass ]]; then
					dunstify "Creating new pass: $new_acc_pass"
					bspc rule -a \* -o state=floating "$TERMINAL" && "$TERMINAL" -e zsh -c "export VISUAL=nvim; pass init $new_acc_pass"
				fi
			elif [[ $1 == "edit_pass" ]]; then
				bspc rule -a \* -o state=floating "$TERMINAL" && "$TERMINAL" -e zsh -c "export VISUAL=nvim; pass edit $mypass"
			fi
		}

		selection="$(echo -e "copy username\ncopy password\nopen url\nedit\ncreate pass" | $ROFI_COMMAND -dmenu -matchin fuzzy -i -sort -sorting-method fzf -p "$1")"

		if [[ -n "$selection" ]]; then
			if [[ $selection == "copy username" ]]; then
				copy_pasword_or_username "username"
			fi
			if [[ $selection == "copy password" ]]; then
				copy_pasword_or_username "password"
			fi
			if [[ $selection == "open url" ]]; then
				copy_pasword_or_username "url"
			fi
			if [[ $selection == "create pass" ]]; then
				case "$XDG_SESSION_DESKTOP" in
				"bspwm") bspwm_open_float "create_pass" ;;
				"awesome") wm_awesome ;;
				*) exit ;;
				esac
			fi
			if [[ $selection == "edit" ]]; then
				case "$XDG_SESSION_DESKTOP" in
				"bspwm") bspwm_open_float "edit_pass" ;;
				"awesome") wm_awesome ;;
				*) exit ;;
				esac
			fi
			# eval "$options[${(q)selection}]"
		else
			exit 1
		fi
	}

	dir="${PASSWORD_STORE_DIR:-$HOME/.password-store/}"
	password_selection="$(select_password "$1")"
	echo "$password_selection" >/tmp/mypass
	if [[ -n "$password_selection" ]]; then
		select_command "$password_selection" "$1"
	fi

	[[ -f /tmp/mypass ]] && rm /tmp/mypass
	exit
}

main() {
	for i in $(seq 0 $((OBJ_LENGTH - 1))); do
		if [ "$OBJ_SELECTED" = "Add:New:Query" ]; then
			add_query
		fi

		if [ "$OBJ_SELECTED" = "Add:New:Bookmark" ]; then
			add_bookmark
		fi

		if [ "$OBJ_SELECTED" = "Open:Bookmarked" ]; then
			open_bookmarked
		fi

		if [ "$OBJ_SELECTED" = "Delete:Query" ]; then
			delete_query "DMENU" "$FILE"
		fi

		if [ "$OBJ_SELECTED" = "Delete:Bookmarked" ]; then
			delete_query "ROFI" "$FILE_BOOKMARKED"
		fi

		if [ "$OBJ_SELECTED" = "Edit:Bookmarked" ]; then
			edit_bookmarked
		fi

		if [ "$OBJ_SELECTED" = "Open:Pass" ]; then
			open_pass ""
		fi

		if [ "$OBJ_SELECTED" = "$(echo "$OPTIONS" | jq -r --arg i "$i" '.[($i|tonumber)][0]')" ]; then
			URLQUERY=$(echo "$OPTIONS" | jq -r --arg i "$i" '.[($i|tonumber)][1]')
			KEYWORDS=$(echo "$OBJ_KEYWORDS")
			xdg-open "${URLQUERY}${KEYWORDS}" 2>/dev/null
		fi
	done
}

main
