#!/bin/bash
# taken from: https://github.com/bandithijo/dmenu-websearch

MENU="dmenu"
FILE="$HOME/Dropbox/data.programming.forprivate/urlquery"
FILE_BOOKMARKED="$HOME/Dropbox/data.programming.forprivate/urlbookmarked"

ROFI_DIR="$HOME/.config/rofi/menu"
ROFI_THEME="styles/snippets"
ROFI_COMMAND="rofi -theme $ROFI_DIR/$ROFI_THEME"

test_file_dir() {
	if [ ! -f "$1" ]; then
		if command -v dunstify >/dev/null; then
			dunstify "$2"
		else
			echo "$2"
		fi
		touch "$1"
		exit
	fi
}

NOTIFY_ME="[ERROR]: file $FILE not found"
NOTIFY_ME_BOOKMARKED="[ERROR]: file $FILE_BOOKMARKED not found"

test_file_dir "$FILE" "$NOTIFY_ME"
test_file_dir "$FILE_BOOKMARKED" "$NOTIFY_ME_BOOKMARKED"

FILEOPT=$(cat "$FILE")

OPTIONS="
[
${FILEOPT}
[ \"Add:New:Query\", \"\" ],
[ \"Add:New:Bookmark\", \"\" ],
[ \"Open:Bookmarked\", \"\" ],
[ \"Delete:Query\",  \"\" ],
[ \"Delete:Bookmarked\",  \"\" ],
[ \"Edit:Bookmarked\",  \"\" ],
[ \"Open:Pass\",  \"\" ]
]
"

OBJ_LENGTH=$(echo "$OPTIONS" | jq length)
OBJ_MENU=$(echo "$OPTIONS" | jq -r ".[][0]" | $MENU -i -p " WebSearch:")
OBJ_SELECTED=$(echo "$OBJ_MENU" | cut -d' ' -f1)
OBJ_KEYWORDS=$(echo "$OBJ_MENU" | cut -d' ' -f2- | tr " " "+")

add_query() {
	PREFIXMENU=$(echo "" | dmenu -p "Add prefix menu:" <&-)
	if [ -n "$PREFIXMENU" ]; then
		URLQUERY=$(echo "" | dmenu -p "Add url query:" <&-)
		echo "[ \"$PREFIXMENU\", \"$URLQUERY\" ]," >>"$FILE"
	fi
	exit
}

delete_query() {
	if [ "$1" == "DMENU" ]; then
		OBJ_MENU=$(echo "$OPTIONS" | jq -r ".[][0]" | head -n -2 | $MENU -i -p "Delete Menu:")
	else
		OBJ_MENU=$(awk -F"," '{printf "%-10s%s%-10s%s%-10s\n", $1,OFS,$2,OFS,$3}' OFS="," "$FILE_BOOKMARKED" |
			sort | awk -F"," '{print $1,$3}' |
			column -t -s"+" | $ROFI_COMMAND -dmenu -i -p "  " | awk -F"[[:space:]][[:space:]][[:space:]]+" '{print $1}')
	fi

	OBJ_SELECTED=$OBJ_MENU

	if [ -n "$OBJ_SELECTED" ]; then
		CONFIRM_DELETE=$(echo -e "no\nyes" | dmenu -p "Do you want to delete this url?")
		if [ "$CONFIRM_DELETE" = "yes" ]; then
			sed -i "/$OBJ_SELECTED/d" "$2"
		fi
	fi
	exit
}

add_bookmark() {
	GET_CLIPCOPY=$(xclip -selection c -o)
	if [ -z "$GET_CLIPCOPY" ]; then
		dunstify "url: empty, abort"
		exit
	fi

	SET_TAGS=$(echo -e "hacky\ndotfiles\ntodo\ntutorial\ntorrent\nforum\ngithub\nTODO\nfun\ntips\ndevs\nmoneygame\nwallpaper" | dmenu -p "Tags:")
	if [ -z "$SET_TAGS" ]; then
		dunstify "tags: empty, abort"
		exit
	fi

	DESCRIPTION=$(echo "" | dmenu -p "Add description:" <&-)

	if [ -n "$DESCRIPTION" ]; then
		# PREFIX_DAT=$(echo "$GET_CLIPCOPY" | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')
		dunstify "url: $GET_CLIPCOPY adding to our bookmarked"
		# echo "$DESCRIPTION,$SET_TAGS,$PREFIX_DAT,+$GET_CLIPCOPY" >>"$FILE_BOOKMARKED"
		echo "$DESCRIPTION,$SET_TAGS,+$GET_CLIPCOPY" >>"$FILE_BOOKMARKED"
	fi
	exit
}

open_bookmarked() {
	# OPTIONS=$(cat "$FILE_BOOKMARKED" | sort | $ROFI_COMMAND -dmenu -i -p "  " | cut -d"," -f2)
	OPTIONS=$(
		awk -F"," '{printf "%-10s%s%-10s%s%-10s\n", $1,OFS,$2,OFS,$3}' OFS="," "$FILE_BOOKMARKED" |
			sort | column -t -s"," | $ROFI_COMMAND -dmenu -i -p "  " |
			tr -s " " | awk -F"+" '{print $2}'
	)
	xdg-open "$OPTIONS" 2>/dev/null
	exit
}

edit_bookmarked() {
	# kalau bukan bspwm, ini bakal error
	bspc rule -a \* -o state=floating center=true rectangle=800x500+0+0 && kitty -e bash -c "/usr/local/bin/nvim ~/Dropbox/data.programming.forprivate/urlbookmarked"

	exit
}

open_pass() {

	timeout=30
	dir="$HOME/.config/rofi/menu"
	theme="styles/big_center"
	rofi_command="rofi -theme $dir/$theme -dmenu -matchin fuzzy -i -sort -sorting-method fzf "

	# kalau bukan bspwm, ini bakal error
	# bspc rule -a \* -o state=floating center=true rectangle=800x500+0+0 && kitty -e bash -c "/usr/local/bin/nvim ~/Dropbox/data.programming.forprivate/urlbookmarked"

	select_command() {
		# contents="$(pass show "$1")"
		# first_line="$(head -1 <<< "$contents")"
		# the_password
		# the_username
		# the_url
		# if [[ ! "${first_line}" =~ ": " ]]; then
		#   options[Copy\ password]="wl-copy ${(q)first_line}"
		#   options_order+="Copy password"
		#   the_password="$first_line"
		# fi

		# grep -P '^[^:]+(?=: .)' <<< "$contents" | while read line; do
		#   field="${line%%: *}"
		#   value="${line#*: }"
		#   if [[ "$field" == "url" ]]; then
		#     options[Open\ URL]="xdg-open ${(q)value}"
		#     options_order+="Open URL"
		#     the_url="$value"
		#   else
		#     options[Copy\ $field]="wl-copy ${(q)value}"
		#     options_order+="Copy $field"
		#     [[ "$field" == "username" ]] && the_username="$value"
		#   fi
		# done

		# options[Show]="zenity --info --title=${(q)1} --icon-name=password --text=${(q)contents} --width=400"
		# options_order+="Show"

		# if [[ -n "$the_username" ]] && [[ -n "$the_password" ]]; then
		#   options[Copy\ username\ \&\ password]="wl-copy ${(q)the_username} && wl-copy ${(q)the_password} -p"
		#   options_order=("Copy username & password" "${options_order[@]}")
		#   if [[ -n "$the_url" ]]; then
		#     options[Copy\ username\ \&\ password,\ open\ URL]="xdg-open ${(q)the_url} && wl-copy ${(q)the_username} && wl-copy ${(q)the_password} -p"
		#     options_order=("Copy username & password, open URL" "${options_order[@]}")
		#   fi
		# fi
		selection="$(echo -e "copy username\ncopy password\nopen url" | $rofi_command -p "$1")"

		if [[ -n "$selection" ]]; then
			dunstify "$selection"
			# eval "$options[${(q)selection}]"
		else
			exit 2
		fi
	}

	select_password() {
		find "$dir" -not -path '*/.git/*' -type f |
			grep '\.gpg$' |
			sed "s:$dir\(.*\)\.gpg$:\1:" |
			$rofi_command -p 'password' -filter "$1"
	}

	main() {
		dir="${PASSWORD_STORE_DIR:-$HOME/.password-store/}"
		password_selection="$(select_password "$1")"
		if [[ -n "$password_selection" ]]; then
			select_command "$password_selection" "$1"
			sleep $timeout && eval "wl-copy -c && wl-copy -cp"
		else
			exit
		fi
	}

	main "$@"

	exit
}
main() {
	for i in $(seq 0 $((OBJ_LENGTH - 1))); do
		if [ "$OBJ_SELECTED" = "Add:New:Query" ]; then
			add_query
		fi

		if [ "$OBJ_SELECTED" = "Add:New:Bookmark" ]; then
			add_bookmark
		fi

		if [ "$OBJ_SELECTED" = "Open:Bookmarked" ]; then
			open_bookmarked
		fi

		if [ "$OBJ_SELECTED" = "Delete:Query" ]; then
			delete_query "DMENU" "$FILE"
		fi

		if [ "$OBJ_SELECTED" = "Delete:Bookmarked" ]; then
			delete_query "ROFI" "$FILE_BOOKMARKED"
		fi

		if [ "$OBJ_SELECTED" = "Edit:Bookmarked" ]; then
			edit_bookmarked
		fi

		if [ "$OBJ_SELECTED" = "Open:Pass" ]; then
			open_pass ""
		fi

		if [ "$OBJ_SELECTED" = "$(echo "$OPTIONS" | jq -r --arg i "$i" '.[($i|tonumber)][0]')" ]; then
			URLQUERY=$(echo "$OPTIONS" | jq -r --arg i "$i" '.[($i|tonumber)][1]')
			KEYWORDS=$(echo "$OBJ_KEYWORDS")
			xdg-open "${URLQUERY}${KEYWORDS}" 2>/dev/null
		fi
	done
}

main
